### ISSUE TITLE
Home Screen Update

### ISSUE THREAD

**Issue by himanshusharma89** [himanshusharma89/relic_bazaar#100]
Update the Home screen for the following:

- [ ] Add never scroll physics in GridView
- [ ] Divide the view into different widgets methods which are being called in the Column inside build method.

# Discussion 🗣
Improve the home screen code by dividing the widgets into different Widget methods. And do resolve the problems in the terminal if it arises.

## Context
For better readability of the code, this needs to be done.

**Comment by Chirag018** [comment]
Can I work on this update ?

**Comment by himanshusharma89** [comment]
> Can I work on this update ?

Are you participating in GSSOC?

**Comment by Chirag018** [comment]
Yes

**Comment by himanshusharma89** [comment]
> Yes

Assigned
