### ISSUE TITLE
Update the Product List

### ISSUE THREAD

**Issue by himanshusharma89** [himanshusharma89/relic_bazaar#101]
Update the Product List in constants.dart to use the Product model instead of passing multiple fields.

# Discussion 🗣
Instead of passing multiple fields pass the Product model object (data being saved in the constructor.)

## Context
Utilize the existing Product model, which will help us in future while handling the API calls.

**Comment by believeInJha** [comment]
I would like to work on this as a part of GSSoC'21, could you please assign it to me and guide me with the process?

**Comment by himanshusharma89** [comment]
> I would like to work on this as a part of GSSoC'21, could you please assign it to me and guide me with the process?

Sure, you are assigned.

**Comment by believeInJha** [comment]
Thanks for the opportunity @himanshusharma89, I will make it as soon as possible and send a PR.

**Comment by D-Ajay-Kumar** [comment]
Still being worked upon or can I take it?

**Comment by believeInJha** [comment]
Hi @D-Ajay-Kumar actually I'm working on this and most probably create a PR by today EOD.

**Comment by D-Ajay-Kumar** [comment]
Okay @believeInJha all the best :)

**Comment by believeInJha** [comment]
@D-Ajay-Kumar  thanks man and same to you!

**Comment by D-Ajay-Kumar** [comment]
Is it done? You need any kind of help @believeInJha ?

**Comment by believeInJha** [comment]
Yes @D-Ajay-Kumar, actually I'm not able to figure out how to cast `ProductCard` into `Product` class. As `ProductCard` is a widget and `Product` is a class, hence I'm unable to figure that out, can you please give me some insight into this, it will be really helpful to me!

**Comment by D-Ajay-Kumar** [comment]
You have to do 2 things -
1. Go to the ProductCard widget and make it accept only one argument, a Product object.
2. Go to the constants file and in the list of ProductCard make all the ProductCard accept not multiple fields but a single Product object.

Instead of 

const ProductCard(
    text: 'ANTIQUE VASE',
    owner: 'by Lloyd Duran',
    amount: '₹ 4035',
    image: 'assets/items/3.png',
    seller: 'Monzart',
    height: 51,
  ),


Do this

const ProductCard(
    product: Product(
      text: 'ANTIQUE VASE',
      owner: 'by Lloyd Duran',
      amount: '₹ 4035',
      image: 'assets/items/3.png',
      seller: 'Monzart',
      height: 51,
    ),
  ),

**Comment by believeInJha** [comment]
@D-Ajay-Kumar, thank you from the bottom of my heart, it worked^-*

**Comment by D-Ajay-Kumar** [comment]
You're welcome man @believeInJha
