### ISSUE TITLE
Adding SafeArea widget on home.dart to avoid cutting off of screen

### ISSUE THREAD

**Issue by D-Ajay-Kumar** [himanshusharma89/relic_bazaar#103]
Currently there is no SafeArea widget because of which there is a possibility of drawer button getting cut by the top bar that show battery percentage on phones with smaller screen size.

**Comment by D-Ajay-Kumar** [comment]
If the issue is accepted then I can do it.

**Comment by pranjalagrawal2012** [comment]
Hey ,@D-Ajay-Kumar @SapinderSingh @Tushar-OP @lordvins226 @anushbhatia if this  issue is active and assigned to nobody then i would be grateful if you can assign me on this issue ?

**Comment by himanshusharma89** [comment]
Hey @pranjalagrawal2012, this issue needs to be discussed before proceeding to it. I'll update this issue as soon as possible.

**Comment by abhishek7997** [comment]
Can I do it, if no one will be assigned? @D-Ajay-Kumar

**Comment by Rishabh510** [comment]
> Hey @pranjalagrawal2012, this issue needs to be discussed before proceeding to it. I'll update this issue as soon as possible.

I think we can assign someone on this issue as SafeArea is important, especially when working with devices with notched display.

**Comment by D-Ajay-Kumar** [comment]
Yeah sure

**Comment by pranjalagrawal2012** [comment]
I can work on this @Rishabh510

**Comment by himanshusharma89** [comment]
> Yeah sure

You can work on it as you created this issue and if you are not assigned to any other issue.

**Comment by D-Ajay-Kumar** [comment]
Sure I'll add Safe Area to every Scaffold in the app

**Comment by D-Ajay-Kumar** [comment]
Done. Please check the code :)

**Comment by believeInJha** [comment]
hey @himanshusharma89, Can I take up this issue?
