### ISSUE TITLE
Bug Fix in Code.

### ISSUE THREAD

**Issue by RGTechno** [himanshusharma89/relic_bazaar#105]
# Bug Report 🐛

## Expected Behavior

Code should build properly.

## Current Behavior

 App is not building due to errors in code.

## Possible Solution

 Settings.dart file and Profile.dart have bugs in it. Resolving it will build it.

Please assign this issue to me. @himanshusharma89

**Comment by D-Ajay-Kumar** [comment]
What kind of bugs does it have?

**Comment by RGTechno** [comment]
Code is not building.

**Comment by himanshusharma89** [comment]
> Code is not building.

Can you attach a screenshot of the error.

**Comment by RGTechno** [comment]
![image](https://user-images.githubusercontent.com/65856344/110907495-7f76e080-8333-11eb-8791-c1842b4b850b.png)
This is the error,

**Comment by RGTechno** [comment]
![image](https://user-images.githubusercontent.com/65856344/110907857-05932700-8334-11eb-9f48-480c30e2febf.png)
@himanshusharma89

**Comment by D-Ajay-Kumar** [comment]
There's just couple of imports missing in the settings.dart file. Who created that file without material.dart file? lol

**Comment by D-Ajay-Kumar** [comment]
Oh I'm sorry I didn't mean to send a PR here but only in my forked repo. Is there any way to delete this PR?

**Comment by Rishabh510** [comment]
@himanshusharma89 The bug is there due to PR #97 . There is problem in lib/views/profile.dart and lib/views/settings.dart files. Also code formatting is required.

**Comment by himanshusharma89** [comment]
Just checked it, thanks for the issue @RGTechno, as you created this issue, would you like to work on this? (if not assigned to any other issue).

**Comment by anotherwebguy** [comment]
> Just checked it, thanks for the issue @RGTechno, as you created this issue, would you like to work on this? (if not assigned to any other issue).

can i work on this i've already fixed the issue should i make a pr?

**Comment by RGTechno** [comment]
Yeah..Definitely I would work on this issue and i am not assigned to any issue

**Comment by RGTechno** [comment]
> Just checked it, thanks for the issue @RGTechno, as you created this issue, would you like to work on this? (if not assigned to any other issue).

@himanshusharma89 assign this issue to me and I'll send a pr.
Thanks
