### ISSUE TITLE
Refactor the project according to lint rules.

### ISSUE THREAD

**Issue by SapinderSingh** [himanshusharma89/relic_bazaar#109]
I can work on this issue. I am a participant of GSSOC 21. I will refactor the whole code according to lint rules.

**Comment by himanshusharma89** [comment]
> I can work on this issue. I am a participant of GSSOC 21. I will refactor the whole code according to lint rules.

Thanks for the issue but your refactoring won't do anything as multiple contributors might skip it on the next PR. So this issue will be handled during the deployment of the app.

**Comment by Rishabh510** [comment]
> > I can work on this issue. I am a participant of GSSOC 21. I will refactor the whole code according to lint rules.
> 
> Thanks for the issue but your refactoring won't do anything as multiple contributors might skip it on the next PR. So this issue will be handled during the deployment of the app.

VS code and Android Studio both have excellent internal refactoring methods. Closing this issue.
