### ISSUE TITLE
App Release action is failing

### ISSUE THREAD

**Issue by aayushbisen** [himanshusharma89/relic_bazaar#122]
# Bug Report 🐛

## Expected Behavior
App release action should build the apk and create a new release.

## Current Behavior
The action is failing in installing dependencies stage.

## Possible Solution
Update the App release workflow to use the current Flutter version.

## Steps to Reproduce
The issue can be reproduced when any new commit is pushed to master branch.

**Comment by Rishabh510** [comment]
@himanshusharma89 There hasn't been any update on this issue. Anyone else want to take up this issue?
