### ISSUE TITLE
Order Model

### ISSUE THREAD

**Issue by himanshusharma89** [himanshusharma89/relic_bazaar#125]
Similar to the Product model create the Order model

# Discussion 🗣
The model needs to be created to handle API data.

**Comment by D-Ajay-Kumar** [comment]
Can do it. Where can I find the attributes list that we'll get from the API?

**Comment by himanshusharma89** [comment]
> Can do it. Where can I find the attributes list that we'll get from the API?

Check the order_item.dart in widgets for the fields. And you just need to create the model for now. I'll create a separate issue to handle the data.

**Comment by D-Ajay-Kumar** [comment]
That's all right?

![order model](https://user-images.githubusercontent.com/56850266/111064602-fc908a00-84da-11eb-976f-633cb5296138.PNG)

**Comment by D-Ajay-Kumar** [comment]
Should I also change the profile.dart file to pass Order object to order_item.dart instead of the individual attributes?

**Comment by himanshusharma89** [comment]
> Should I also change the profile.dart file to pass Order object to order_item.dart instead of the individual attributes?

Not for now, there are a lot of issues assigned on Profile Screen, we need to wait till it is resolved. I'll create a separate issue for the Product and Order Model altogether

**Comment by D-Ajay-Kumar** [comment]
> > Should I also change the profile.dart file to pass Order object to order_item.dart instead of the individual attributes?
> 
> Not for now, there are a lot of issues assigned on Profile Screen, we need to wait till it is resolved. I'll create a separate issue for the Product and Order Model altogether

Okay then I'll push just this code

**Comment by D-Ajay-Kumar** [comment]
Done. Please check the code :)
