### ISSUE TITLE
Deploy APK Action

### ISSUE THREAD

**Issue by himanshusharma89** [himanshusharma89/relic_bazaar#13]

**Comment by Mastersam07** [comment]
Where should the apk be deployed to? Github release?

**Comment by himanshusharma89** [comment]
Yes @Mastersam07

**Comment by lordvins226** [comment]
i will try this issue and make PR

**Comment by himanshusharma89** [comment]
Ok @lordvins226, assigned to you

**Comment by ecrax** [comment]
I would have a workflow file ready. It generates a new version number, then builds and tests the build, and then makes a GitHub release with the newest version number and the built apk as an artifact.

I could create a pull request with the workflow file :)

**Comment by lordvins226** [comment]
Make your PR

**Comment by himanshusharma89** [comment]
@ecrax perfect! go ahead create a PR

**Comment by ecrax** [comment]
@himanshusharma89 I have added a PR referencing this issue

**Comment by ecrax** [comment]
Isn't this issue ready to close?

**Comment by himanshusharma89** [comment]
Yeah @ecrax, closing it. I thought you mentioned this issue in the PR (as Fixes #13) to automatically delete this issue.
