### ISSUE TITLE
Adding CONTRIBUTORS.md file

### ISSUE THREAD

**Issue by rajeshpanjiyar** [himanshusharma89/relic_bazaar#135]
**Hi,** I would like to add a contributors file to add the **name and GitHub handle** of valuable contributors.
- I am a participant under GSSoC'21

**Comment by himanshusharma89** [comment]
Hey @rajeshpanjiyar, we already have a bot to do that, so this issue is not required.

**Comment by rajeshpanjiyar** [comment]
Okay you can close this
