### ISSUE TITLE
Use Native Splash Screen

### ISSUE THREAD

**Issue by AJAYK-01** [himanshusharma89/relic_bazaar#138]
## Discussion :speaking_head:
I'm a participant of GSSOC '21 and wish to open my first issue in this project and the program.

The app currently uses Flutter splash screen with a timer of 3 seconds.
Native splash screen replaces the initial white screen (app initialising time) with our required splash screen.

## Context
This port needs to be done to improve the user's experience as the Flutter splash screen simply wastes the user's time with the 3 second delay which is added time above the already app initialising time.

## Detailed Description
I wish to port the splash screen to native one using the flutter_native_splash package which can generate native splash screen for both android and ios, allowing to use an image and a background that replaces the initial white splash screen without wasting the user's time.

I can work on this and please assign this issue to me.

**Comment by AJAYK-01** [comment]
I have successfully made the changes, and is ready to PR, but may I know what version number should I change the app to?
Currently it is 1.0.0+1, after adding the native splash screens, what should be the new version number?

**Comment by himanshusharma89** [comment]
> I have successfully made the changes, and is ready to PR, but may I know what version number should I change the app to?
> Currently it is 1.0.0+1, after adding the native splash screens, what should be the new version number?

Don't change it, we are still in development, and it'll be updated after 1st deployment.
