### ISSUE TITLE
add contributors section in readme

### ISSUE THREAD

**Issue by rajeshpanjiyar** [himanshusharma89/relic_bazaar#141]
The ***contributors*** section is the best part of any readme. This issue is to add the contributor's section in the readme. It will add contributors' names automatically so no need to update this issue from time to time.
I am a participant in **GSSoC'21**. I request you to assign me this issue so that I can start working.

**Comment by D-Ajay-Kumar** [comment]
Lol please not this again.

**Comment by himanshusharma89** [comment]
@rajeshpanjiyar You are creating the same issue again. As I have mentioned earlier here: #135, this issue is not required.
