### ISSUE TITLE
Use the named routes to navigate in between pages.

### ISSUE THREAD

**Issue by himanshusharma89** [himanshusharma89/relic_bazaar#151]
Use the named routes to navigate in between pages.

# Discussion 🗣
Use the named routes in constants.dart to navigate in between screen.

## Context
Make sure to use Replacement and RemoveUntil methods appropriately.

**Comment by SapinderSingh** [comment]
Hey @himanshusharma89, I can work on this issue. Please assign it to me.

**Comment by SapinderSingh** [comment]
@himanshusharma89 There is a Cart Button on the top right of home.dart screen, What should I have to do of that button ?

**Comment by himanshusharma89** [comment]
> @himanshusharma89 There is a Cart Button on the top right of home.dart screen, What should I have to do of that button ?

You can use pagecontroller for that, pass it from the dashboard.

**Comment by SapinderSingh** [comment]
@himanshusharma89 same as for the buttons in the drawer ?

**Comment by SapinderSingh** [comment]
@himanshusharma89 and where to navigate when clicked on the "Log Out" Button ?

**Comment by himanshusharma89** [comment]
> @himanshusharma89 same for the buttons in the drawer ?

No, those screens will use Navigator for navigation.

**Comment by himanshusharma89** [comment]
> @himanshusharma89 and where to navigate when clicked on the "Log Out" Button ?

Back to the login screen, using Navigator

**Comment by SapinderSingh** [comment]
@himanshusharma89 Please review my PR
