### ISSUE TITLE
Use the RelicBazaarStackedView widget in place of Stacks for Retro Theme UI

### ISSUE THREAD

**Issue by himanshusharma89** [himanshusharma89/relic_bazaar#152]
Use the StackedContainer widget in place of Stacks for Retro Theme UI

# Discussion 🗣
A lot of UI in the app depends upon the Stack and Transform UI, so instead of repeating the code use the StackedContainer widget for that.

## Context
To remove the repeated code, we will use this widget.

## Detailed Description
Check login.dart and home.dart for the example of StackedContainer

**Comment by SapinderSingh** [comment]
Hey, @himanshusharma89 I want to work on this issue, Please assign it to me

**Comment by Chirag018** [comment]
@himanshusharma89  I can work on this issue, you can assign this issue to me

**Comment by himanshusharma89** [comment]
@Chirag018  You were not able to work on MK Docs earlier. So, will you be able to do this?

**Comment by Chirag018** [comment]
@himanshusharma89 Yes sir.

**Comment by Chirag018** [comment]
@himanshusharma89  sir when I am trying to use stacked container widget I just get problem like what should I do with offset ?

**Comment by himanshusharma89** [comment]
> @himanshusharma89 sir when I am trying to use stacked container widget I just get problem like what should I do with offset ?

Can you attach the error message here

**Comment by Chirag018** [comment]
sir in stacked container we require child , whereas in stack widget we require children how to handle this sir?

**Comment by himanshusharma89** [comment]
> sir in stacked container we require child , whereas in stack widget we require children how to handle this sir?

Check the code again, the StackedContainer contains the Stack and children, so you need to use this StackedContainer in every place where we have Stack to create the design with Transform widget aschildren. And the child will be the other one in the children.

**Comment by Chirag018** [comment]
@himanshusharma89  Can I divide the signup_view.dart file into different widgets/methods which are being called in the Stack widget inside build method.

**Comment by himanshusharma89** [comment]
> @himanshusharma89 Can I divide the signup_view.dart file into different widgets/methods which are being called in the Stack widget inside build method.

No, you don't have to do such things, you just need to remove the Stack and Transform Widget and then other children parent will be replaced with StackedContainer. Check the files that I have mentioned in the issue.

**Comment by Chirag018** [comment]
okay

**Comment by SapinderSingh** [comment]
@himanshusharma89 I can work on this issue.
