### ISSUE TITLE
App is using a Text Widget for unknown route instead of a screen.

### ISSUE THREAD

**Issue by SapinderSingh** [himanshusharma89/relic_bazaar#161]
# Bug Report 🐛
If by chance there is no valid route, user must be navigated to a screen, rather than encountering app crash or errors, but the app is using a Text widget instead of a screen.

## Expected Behavior
If there is no valid route or screen, user must be navigated to a screen saying, unknown route.

## Current Behavior
A black screen, with a text is shown.

## Possible Solution
I will create a new screen, create its route constant and use it in the route_page.dart file as a default case. 

I am the participant of GSSOC 21. Please assign me this issue.

**Comment by himanshusharma89** [comment]
@SapinderSingh I suppose I commented on the default value regarding this and sure, you can work on this. Do follow the Retro theme.
