### ISSUE TITLE
Log in screen overflowing

### ISSUE THREAD

**Issue by AksV73** [himanshusharma89/relic_bazaar#165]
# Bug Report 🐛

The login screen is overflowing in my phone. 
## Expected Behavior

The UI should be uniform for all sizes and shapes of smartphones
## Current Behavior

It is overflowing in my phone
## Possible Solution

I would like to insert a scroll in place in order to solve this issue.

**Comment by himanshusharma89** [comment]
Instead of adding a scroll, can you make the whole screen responsive? You can use Flexible if required. @AksV73

**Comment by AksV73** [comment]
Ok I'll try it out

**Comment by himanshusharma89** [comment]
@AksV73 You can decrease the size of widgets. Are you participating in GSSOC? If so, I'll assign it to you

**Comment by AksV73** [comment]
Yes I am
