### ISSUE TITLE
Delete branch on close PR

### ISSUE THREAD

**Issue by himanshusharma89** [himanshusharma89/relic_bazaar#17]

**Comment by Tushar-OP** [comment]
I would like to try this issue, can you assign it to me?

**Comment by himanshusharma89** [comment]
Sure, @Tushar-OP

**Comment by Tushar-OP** [comment]
I wanted to clarify, do we have to delete the merged branch(because github already natively does this) or what?

**Comment by himanshusharma89** [comment]
@Tushar-OP, Github doesn't automate the process for deleting the branch of merged PR, you need to install a bot or add a GitHub Action.

**Comment by Tushar-OP** [comment]
Okay, so we need to delete the branch of merged PR right?

**Comment by himanshusharma89** [comment]
Yes @Tushar-OP

**Comment by Tushar-OP** [comment]
Okay, @himanshusharma89!

**Comment by Tushar-OP** [comment]
@himanshusharma89  I have created a PR for this, please check it out.
