### ISSUE TITLE
Keep User Logged in

### ISSUE THREAD

**Issue by Mus2413** [himanshusharma89/relic_bazaar#174]
# Feature Request ✨

## Detailed Description

After the user quit the app and returns back , then  they have to logged in again.  I want to add one feature which will keep user signed in .

**Comment by Mus2413** [comment]
I want to add this feature please assign this issue to me.

**Comment by himanshusharma89** [comment]
@ishandeveloper @smaranjitghose @anushbhatia @Rishabh510 Should we use shred preferences here or StreamBuilder?

**Comment by Mus2413** [comment]
Shared preferences

**Comment by ishandeveloper** [comment]
> @ishandeveloper @smaranjitghose @anushbhatia @Rishabh510 Should we use shred preferences here or StreamBuilder?
Shared Prefs seems like a better option to me, what do you think?

**Comment by Rishabh510** [comment]
> @ishandeveloper @smaranjitghose @anushbhatia @Rishabh510 Should we use shred preferences here or StreamBuilder?

Using StreamBuilder we can just check for onAuthChanged flag and direct the user accordingly. Its just like if else and much better as we are anyway requiring internet connection for connecting to Firebase. So it makes sense rather using Shared Prefs.

**Comment by himanshusharma89** [comment]
We have to decide between the two of them. I'll finalise it tomorrow.

**Comment by ishandeveloper** [comment]
> > @ishandeveloper @smaranjitghose @anushbhatia @Rishabh510 Should we use shred preferences here or StreamBuilder?
> 
> Using StreamBuilder we can just check for onAuthStateChanged flag and direct the user accordingly. Its just like if else and much better as we are anyway requiring internet connection for connecting to Firebase. So it makes sense rather using Shared Prefs.
> Including the doc for the same [here](https://firebase.google.com/docs/auth/web/manage-users).

Last time I used Streambuilder with firebase auth, the initial load times for my app to go from splash screen to actual home screen were significantly larger. I believe with the shared prefs approach, that won't be the case. Still, I'm open to the idea of using streambuilder, if that better fits our use case. What do you think?

**Comment by Rishabh510** [comment]
> > > @ishandeveloper @smaranjitghose @anushbhatia @Rishabh510 Should we use shred preferences here or StreamBuilder?
> > 
> > 
> > Using StreamBuilder we can just check for onAuthStateChanged flag and direct the user accordingly. Its just like if else and much better as we are anyway requiring internet connection for connecting to Firebase. So it makes sense rather using Shared Prefs.
> > Including the doc for the same [here](https://firebase.google.com/docs/auth/web/manage-users).
> 
> Last time I used Streambuilder with firebase auth, the initial load times for my app to go from splash screen to actual home screen were significantly larger. I believe with the shared prefs approach, that won't be the case. Still, I'm open to the idea of using streambuilder, if that better fits our use case. What do you think?

We can go with shared_prefs as well. The difference is we connect with Firebase Server when using Streambuilder and with local device storage when using shared_prefs and then later with Firebase Server to initiate login request. Also, we can show the Splash screen only till we get the user authentication status from Firebase and then move over to the Home Page of the application. I recommended Streambuilder since it is easy to work with and doesn't require an extra package.

**Comment by himanshusharma89** [comment]
@Mus2413 You can go ahead with streambuilder for keeping user logged in:
![image](https://user-images.githubusercontent.com/44980497/113430836-7dff7c00-93f8-11eb-98f2-d64bb7679d40.png)

**Comment by Mus2413** [comment]
Okay

**Comment by anotherwebguy** [comment]
Hey @himanshusharma89  we can use FirebaseAuth.Currentuser.uid 
Like we can use it as
FirebaseAuth.Currentuser.uid !=null ? Loginpage : homescreen

This way the user will be signed if he/she hasn't loggedout

Should i work on this issue under gssoc?

**Comment by himanshusharma89** [comment]
@anotherwebguy The above stream will do the same and this issue is already assigned to @Mus2413. BTW @Mus2413, any update on this issue?

**Comment by Mus2413** [comment]
I am working on it...
