### ISSUE TITLE
Login and Sign Credentails Validation

### ISSUE THREAD

**Issue by himanshusharma89** [himanshusharma89/relic_bazaar#177]
Use RegEx to validate the email using TextFormField features.

# Discussion 🗣
Features required to indicate user if the email is not valid.

## Detailed Description
Display the error below the centre UI (Don't show the error below the TextFormField). Also, if the email is correct after don't display the error. (user TextFormField features for that)

**Comment by Neha62-lit** [comment]
@himanshusharma89 I would like to work on this issue!!

**Comment by himanshusharma89** [comment]
Pull the updated code, before working @Neha62-lit

**Comment by himanshusharma89** [comment]
Any update @Neha62-lit?

**Comment by Neha62-lit** [comment]
> Any update @Neha62-lit?

Started with it, will make a PR soon!

**Comment by Neha62-lit** [comment]
@himanshusharma89  Can I use here flutter toast package for display error?
https://pub.dev/packages/fluttertoast

**Comment by himanshusharma89** [comment]
> @himanshusharma89 Can I use here flutter toast package for display error?
> https://pub.dev/packages/fluttertoast

Use snackbar, toasts might not be visible to user

**Comment by Neha62-lit** [comment]
> > @himanshusharma89 Can I use here flutter toast package for display error?
> > https://pub.dev/packages/fluttertoast
> 
> Use snackbar, toasts might not be visible to user

Okay

**Comment by SapinderSingh** [comment]
@himanshusharma89  I can work on this issue.

**Comment by abhishek7997** [comment]
@himanshusharma89 
Can I try to fix this issue?

**Comment by himanshusharma89** [comment]
Sure @abhishek7997

**Comment by SapinderSingh** [comment]
@himanshusharma89  I can work on this issue. Please assign this to me.
