### ISSUE TITLE
Use FocusNode to shift from one TextFormField to another

### ISSUE THREAD

**Issue by himanshusharma89** [himanshusharma89/relic_bazaar#178]
Use FocusNode to shift from one TextFormField to another

# Discussion 🗣
If the user uses the done button in his/her keyboard, the focus should be changed to below textformfield.

## Context
https://medium.com/flutterdevs/focusnode-in-flutter-4a8613d7e4f6

**Comment by Samdid** [comment]
@himanshusharma89 I would like to work on this, please assign it to me. Also, I am a gssoc participant

**Comment by himanshusharma89** [comment]
Pull the updated code, before working @Samdid

**Comment by Samdid** [comment]
Sure

> Pull the updated code, before working @Samdid
