### ISSUE TITLE
Improving tech stack with logos in readme

### ISSUE THREAD

**Issue by srisatya1197** [himanshusharma89/relic_bazaar#180]
I want to improve the tech stack in readme file with logos. I'm a participant of GSSOC'21 please assign this issue to me @himanshusharma89 .

**Comment by himanshusharma89** [comment]
@srisatya1197 Such minor issues are not good for getting the points. If you still want to work on this, let me know if you can deploy mkdocs(check branches other than master)

**Comment by srisatya1197** [comment]
That's completely fine @himanshusharma89 .
