### ISSUE TITLE
Store user data into Cloud Firestore

### ISSUE THREAD

**Issue by himanshusharma89** [himanshusharma89/relic_bazaar#189]
Store the user data after authentication into Cloud Firestore

# Discussion 🗣
Store the user's email, name and uid into Cloud Firestore

**Comment by Mohitmadhav** [comment]
@himanshusharma89 can I take up this issue?

**Comment by himanshusharma89** [comment]
@Mohitmadhav You can work on one issue at a time

**Comment by anotherwebguy** [comment]
I can work on this issue plz assign me this issue
Here's my email id mohitrajputms123@gmail.com
Plz add me on firebase

**Comment by abhishek7997** [comment]
The issue lacks clarity.
Please tell everything that consists of User data.

**Comment by anotherwebguy** [comment]
What all user info do we have to push to cloud firestore? @himanshusharma89

**Comment by himanshusharma89** [comment]
@anotherwebguy mentioned in the description

**Comment by anotherwebguy** [comment]
> @anotherwebguy mentioned in the description

Okay @himanshusharma89

**Comment by anotherwebguy** [comment]
![Screenshot (321)](https://user-images.githubusercontent.com/66346161/115376009-f5505080-a1eb-11eb-9e97-425d94c3668d.png)

hey @himanshusharma89 you will have to enable the cloud firestore since it requires owner permissions

**Comment by himanshusharma89** [comment]
@anotherwebguy Done
