### ISSUE TITLE
Use FutureBuilder to fetch the products

### ISSUE THREAD

**Issue by himanshusharma89** [himanshusharma89/relic_bazaar#190]
Use FutureBuilder to fetch the products

# Discussion 🗣
In the HomeScreen use  FutureBuilder to fetch the products from a method named getProducts (create a service class for that).

## Detailed Description
For now, the getProducts will only fetch the data which is provided in the constants but as a Future.

**Comment by SapinderSingh** [comment]
@himanshusharma89 I would like to work on this issue.

**Comment by Mohitmadhav** [comment]
@himanshusharma89 can I work on this issue?

**Comment by himanshusharma89** [comment]
@Mohitmadhav As I mentioned earlier, one person can work on 1 issue at a time.
