### ISSUE TITLE
Display User data

### ISSUE THREAD

**Issue by himanshusharma89** [himanshusharma89/relic_bazaar#209]
Use the User data to display it in the Home and Profile Screen

# Discussion 🗣
We have saved the user data to firestore , now we need to use that user to display the `name` and `email` in the `home screen` and `profile screen`   

## Context
You can use the existing StreamBuilder in `main.dart` to store the User, or you can propose a different method to do that.

**Comment by anotherwebguy** [comment]
hey @himanshusharma89 i would like to work on this issue under gssoc
 i've an different approach
we will fetch the data in a different class and then we call this method to get the user info wherever we want to display it
here's an example 
![Untitled](https://user-images.githubusercontent.com/66346161/115993786-fae5d600-a5f1-11eb-9f5a-69e19cde8b36.png)

**Comment by himanshusharma89** [comment]
@anotherwebguy Assigned. But talking about the approach, as we already are using StreamBuilder which will give the User stream, we can use your fetchData method(Without FirebaseFirestore Instance call) in line 62 of main.dart and pass down the User and then we can save it locally in a RelicUser Model.

**Comment by anotherwebguy** [comment]
> @anotherwebguy Assigned. But talking about the approach, as we already are using StreamBuilder which will give the User stream, we can use your fetchData method(Without FirebaseFirestore Instance call) in line 62 of main.dart and pass down the User and then we can save it locally in a RelicUser Model.

We need the data from firestore user collection right? So we have to use firebasefirestore.instance ?

**Comment by himanshusharma89** [comment]
@anotherwebguy  Oh yeah, I forgot about the user's collection, okay, so we can just use the stream to check whether that particular uid exists in the users collection, if so we will pass it to our RelicUser model.

**Comment by anotherwebguy** [comment]
> @anotherwebguy Oh yeah, I forgot about the user's collection, okay, so we can just use the stream to check whether that particular uid exists in the users collection, if so we will pass it to our RelicUser model.

Yes @himanshusharma89 i'll make a pr by tomorrow
