### ISSUE TITLE
Firebase Integration

### ISSUE THREAD

**Issue by himanshusharma89** [himanshusharma89/relic_bazaar#21]
Integrate the project to Firebase Console. 
Share your email address to perform the task

**Comment by Manzee1609** [comment]
Can this issue be described in a more detailed manner, if found suitable I would like to work on this issue for GSSOC'21

**Comment by himanshusharma89** [comment]
@Manzee1609 I'll add new issues and description to all the issue by tomorrow night.

**Comment by Manzee1609** [comment]
Okay! I woukd like to work on this!

**Comment by himanshusharma89** [comment]
Sure @Manzee1609, let's wait till the 8th, then I'll assign it to you

**Comment by himanshusharma89** [comment]
@Manzee1609, can you share your Gmail id? to solve this issue

**Comment by Manzee1609** [comment]
Email - mansikalaria16@gmail.com

**Comment by himanshusharma89** [comment]
Invitation sent @Manzee1609, also refer to this for integration: https://firebase.google.com/docs/flutter/setup?platform=android
