### ISSUE TITLE
Update CONTRUBUTING.md File.

### ISSUE THREAD

**Issue by naman5665** [himanshusharma89/relic_bazaar#216]
# Resolve Gramatically Mistake in CONTRUBUTING.md File.

**Comment by AshuKV** [comment]
Can I work on this issue under GSSoC'21? Kindly assign it to me.

**Comment by himanshusharma89** [comment]
Such issues can not be worked upon on this project, if you want to contribute more, fix the grammatical mistakes and deploy the docs using mkdocs, check documentation and gh-pages branch

**Comment by naman5665** [comment]
@himanshusharma89 So may i close this one issue ??

**Comment by himanshusharma89** [comment]
@naman5665 If you can work on mkdocs let me know, else you can close this.

**Comment by naman5665** [comment]
Ok @himanshusharma89
