### ISSUE TITLE
Show and Hide Password Functionality in Sign-Up and Login Screens

### ISSUE THREAD

**Issue by Neha62-lit** [himanshusharma89/relic_bazaar#223]
# Feature Request ✨
Show and Hide Password Functionality in Sign-Up and Login Screens.

## Use Case
We can see our password when we enter our password at the time of Login and Signup.

## Context
This functionality will be added in both Login and Signup screens.

**Comment by himanshusharma89** [comment]
Hey @Neha62-lit, are you talking about obscure text in password text form fields?

**Comment by Neha62-lit** [comment]
> Hey @Neha62-lit, are you talking about obscure text in password text form fields?

Yes
