### ISSUE TITLE
Fetch products from REST API

### ISSUE THREAD

**Issue by himanshusharma89** [himanshusharma89/relic_bazaar#226]
# Discussion 🗣
Currently, we are fetching the hard-coded products, now you need to fetch the products using a REST API.

## Context
Use this API: https://himanshusharma89-api.herokuapp.com/api/relic_bazaar/products

**Comment by SapinderSingh** [comment]
@himanshusharma89 I can work on this issue

**Comment by SapinderSingh** [comment]
@himanshusharma89 Do I only have to create a method to fetch the products using http ? Or do I have to use it also ? Because, there is no image Url and no height values in the json data.

**Comment by himanshusharma89** [comment]
@SapinderSingh Fetch the data, create a factory constructor in the products model, pass the data, and later use it. You can use a check for an image and use an asset if it is empty or the size isn't greater than 1.
