### ISSUE TITLE
Renderflex Overflow on login and signup page because of redundant icons and TextFields.

### ISSUE THREAD

**Issue by SapinderSingh** [himanshusharma89/relic_bazaar#228]
# Bug Report 🐛

There is a renderflex overflow on login and  signup screens because of redundant icons and text fields. 

## Changes I will do - 

- I will remove all the redundant icons and text fields. 
- I will remove the facebook login icons as @himanshusharma89 said in #89 that app doesn't require facebook login feature.

I can work on this issue as a participant of GSSOC 21. 

## Screenshots - 

![signal-2021-05-06-135952](https://user-images.githubusercontent.com/29424616/117267718-32674480-ae74-11eb-988a-8b543bf8c9dc.jpeg)
![signal-2021-05-06-135954](https://user-images.githubusercontent.com/29424616/117267725-33987180-ae74-11eb-85de-cde39cd5391f.jpeg)

**Comment by himanshusharma89** [comment]
I'll fix the UI and make it responsive to any screen

**Comment by SapinderSingh** [comment]
Hey @himanshusharma89, if you haven't started working on this, then I would love to work on this issue.

**Comment by himanshusharma89** [comment]
> Hey @himanshusharma89, if you haven't started working on this, then I would love to work on this issue.

Yeah, I am not getting time for that. Assigning this to you, try to use Expanded, Flexible, with FittedBox. It'll help to make the screen responsive.

**Comment by SapinderSingh** [comment]
> > Hey @himanshusharma89, if you haven't started working on this, then I would love to work on this issue.
> 
> Yeah, I am not getting time for that. Assigning this to you, try to use Expanded, Flexible, with FittedBox. It'll help to make the screen responsive.

Okay Sir !
