### ISSUE TITLE
Value is not submitted unless user taps on the next or done buttons of soft keyboard on login and sign up screen.

### ISSUE THREAD

**Issue by SapinderSingh** [himanshusharma89/relic_bazaar#235]
# Bug Report 🐛
while filling the login or sign up form, if user doesn't taps on the next or done buttons of every text field, the value is not submitted and it gives Invalid request as error. 

## Expected Behavior
Even if user doesn't taps on done or next buttons, all the values should be submitted, when user taps on the submit button.

## Steps to Reproduce
1. Go to login or sign up screen. 
2. Don't tap on the next or submit button, 
3. Click on the submit button directly after filling
4. See the error

### Please assign me this issue under GSSOC 21.

**Comment by himanshusharma89** [comment]
@SapinderSingh Can you show me the error?

**Comment by SapinderSingh** [comment]
@himanshusharma89 Sure.

**Comment by SapinderSingh** [comment]
### Here it is - 
https://user-images.githubusercontent.com/29424616/118381442-7858a100-b608-11eb-9133-9a4eba7eec8c.mp4
