### ISSUE TITLE
Razorpay: Payment Gateway Integration

### ISSUE THREAD

**Issue by himanshusharma89** [himanshusharma89/relic_bazaar#24]
Use the [Razorpay package](https://pub.dev/packages/razorpay_flutter) to integrate its payment gateway in the app.

**Comment by nb9960** [comment]
Are the APIs (verify payment and one to retrieve razorpay order id) for razorpay integration ready? If yes, then I would like to work on this.

**Comment by himanshusharma89** [comment]
@nb9960 The API's are generally available to use, for this issue you just need to integrate the Razorpay gateway and open the checkout window in the release build. I'll create a separate issue for creating the payment flow with Nodejs endpoints for the webhook URL.

**Comment by nb9960** [comment]
Okay, then I would like to work on this issue as a part of GSSoC'21

**Comment by himanshusharma89** [comment]
@nb9960, I'll assign this issue on the 8th when the coding period starts

**Comment by himanshusharma89** [comment]
@nb9960 Can you just integrate it and test it with the cart screen with the button, to open the checkout window? I am assigning this issue to you

**Comment by nb9960** [comment]
Sure, but for that too one test razorpay API would be required. Can you please provide that?

**Comment by himanshusharma89** [comment]
@nb9960 Check this: https://pub.dev/packages/razorpay_flutter

**Comment by nb9960** [comment]
> @nb9960 Check this: https://pub.dev/packages/razorpay_flutter

This is just a package description and doesn't describe the complete requisites. Refer to this official razorpay docs https://razorpay.com/docs/payment-gateway/flutter-integration/ . Though I have integrated using the test key provided in these docs but still you'll have to generate the key for your project.

**Comment by himanshusharma89** [comment]
@nb9960 You need to add these rules also: https://github.com/razorpay/razorpay-flutter/issues/42#issuecomment-550161626
And test the app with the release build in your app.

**Comment by nb9960** [comment]
> @nb9960 You need to add these rules also: [razorpay/razorpay-flutter#42 (comment)](https://github.com/razorpay/razorpay-flutter/issues/42#issuecomment-550161626)
> And test the app with the release build in your app.

These set of lines are required only if proguard is enabled and since proguard is not enabled for this application it's working absolutely fine in release mode too.

**Comment by himanshusharma89** [comment]
Ohh I suppose they updated the package as it was not working on release mode in earlier versions. Cool, I'll verify the code and merge it.
