### ISSUE TITLE
Update Sign-Up flow

### ISSUE THREAD

**Issue by himanshusharma89** [himanshusharma89/relic_bazaar#241]
# Discussion 🗣
Update the signup flow so that user don't have to sign up again if he/she close the app in between.
This flow will let the user upload picture in the user details form later.

**Comment by Rishabh510** [comment]
Wasn't this issue already handled when we were discussing what to use between SharedPrefs and StreamBuilder?

**Comment by himanshusharma89** [comment]
@Rishabh510 We need to update it to store the user profile pic in Firebase Storage in the User Details form
