### ISSUE TITLE
Implementing Search

### ISSUE THREAD

**Issue by himanshusharma89** [himanshusharma89/relic_bazaar#25]
Implement search functionality in the app to search the products.

**Comment by diksh735** [comment]
I would like to work on this. Please assign me this task.

**Comment by himanshusharma89** [comment]
@diksh735 I can assign it to you, but you have to wait till I update the details/illustrations of each issue

**Comment by himanshusharma89** [comment]
@diksh735 I just saw that you created a PR for App Drawer, so I'll remove this task from you until that one is done.

**Comment by diksh735** [comment]
Okay

**Comment by diksh735** [comment]
So should I do this or generate a new PR for App Drawer ?

**Comment by himanshusharma89** [comment]
@diksh735 Create a PR for App Drawer only as it is the issue assigned to you.

**Comment by DevilAJ** [comment]
I would like go with issue. Please assign me..

**Comment by Saransh-cpp** [comment]
Are you thinking of implementing the search feature with Flutter's SearchDelegate or by using a plugin?

**Comment by himanshusharma89** [comment]
We can discuss this @Saransh-cpp. In the end, we will search the Product object. So we can use SearchDelegate for that.

**Comment by Saransh-cpp** [comment]
> We can discuss this @Saransh-cpp. In the end, we will search the Product object. So we can use SearchDelegate for that.

Great! You can assign it to the person who commented first, I have some prior experience in using SearchDelegate so I'll be here to help.

**Comment by himanshusharma89** [comment]
Sure @Saransh-cpp, but first we need to get the products from an API, if you have any Open API to use, for now, do let me know.

**Comment by himanshusharma89** [comment]
@diksh735 I'll assign this issue to you, as soon as we can setup FutureBuilders

**Comment by himanshusharma89** [comment]
> Are you looking to create and store product details in a database and then access them through an API or get them directly from an existing API? I used firestore to store self written products for an e-commerce app and then access them from there but it has some storage limits.

We are thinking of using API to get the products list, we can use any type of example API for now. Later we'll discuss the backend.

**Comment by himanshusharma89** [comment]
@diksh735 Are you interested in working on this issue? If so, let me know.

**Comment by diksh735** [comment]
I am actually busy right now.

**Comment by SapinderSingh** [comment]
@himanshusharma89 I can work on this issue.
