### ISSUE TITLE
Password Visibility Icons on Authorization pages are inverted 

### ISSUE THREAD

**Issue by Atharv-Joshi** [himanshusharma89/relic_bazaar#258]
# Bug Report 🐛
### Visibility Icons in Authorization pages are inverted

When password is hidden the icon should be 
![Screenshot 2021-11-10 004639](https://user-images.githubusercontent.com/53505850/140989901-4f655dab-290f-48b7-a8ab-c2a3b09893af.png)
while it is 
![Screenshot 2021-11-10 004719](https://user-images.githubusercontent.com/53505850/140990016-c3a85056-8726-423d-8d8e-3f8eece26a4f.png)
Also the colors aren't consistent with app theme 
## Expected Behavior

When password is hidden the icon should be 
![Screenshot 2021-11-10 004639](https://user-images.githubusercontent.com/53505850/140989901-4f655dab-290f-48b7-a8ab-c2a3b09893af.png)
while it is 
![Screenshot 2021-11-10 004719](https://user-images.githubusercontent.com/53505850/140990016-c3a85056-8726-423d-8d8e-3f8eece26a4f.png)
When password is visible the icon color can be warning color and if hidden it can be primary color or background color

![Screenshot 2021-11-10 005440](https://user-images.githubusercontent.com/53505850/140991031-89b3dd62-ff0e-445d-8f18-c3719d86b6d4.png)

I would also like to add a back button to login page from sign up page as is already present from login to signup
## Current Behavior

When password is hidden the icon is 
![Screenshot 2021-11-10 004719](https://user-images.githubusercontent.com/53505850/140990016-c3a85056-8726-423d-8d8e-3f8eece26a4f.png)
instead of 
![Screenshot 2021-11-10 004639](https://user-images.githubusercontent.com/53505850/140989901-4f655dab-290f-48b7-a8ab-c2a3b09893af.png)
Also the colors aren't consistent with app theme 
## Possible Solution

inverting icon names in codebase

## Steps to Reproduce

1. No specific conditions needed. 
2. IS present on Login and Signup Page

### Desktop
 - OS: [e.g. macOS]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 0.22.15]

**Comment by Atharv-Joshi** [comment]
Can I work on  this?

**Comment by warpaltarpers** [comment]
I don't think this is a bug; while "flip-flop" buttons like the one in question aren't considered the best option because they don't tell you the current state, the standard is that the icon should show **what will happen when you click/tap on it**. So, the current behavior lines up with the standard.

**Comment by Atharv-Joshi** [comment]
Yeah , the button state confused me for a second while exploring the app , ig something like show/hide would be more appropriate?

**Comment by himanshusharma89** [comment]
Hi @Atharv-Joshi, pardon me for the delayed response. Sure, you can work on this.

**Comment by Atharv-Joshi** [comment]
> Hi @Atharv-Joshi, pardon me for the delayed response. Sure, you can work on this.

No problem!
