### ISSUE TITLE
App Drawer

### ISSUE THREAD

**Issue by himanshusharma89** [himanshusharma89/relic_bazaar#26]
Create an app drawer in the dashboard and invoke it from the home using Global Scaffold State key

**Comment by diksh735** [comment]
Hello! 
Hope you are doing well!
I am Diksha Goyal student of NIT Delhi and I have already worked on Flutter and I really liked the idea of your project. 
Can I contribute in the same.

**Comment by himanshusharma89** [comment]
Sure @diksh735, you can contribute to the project. But, first, are you participating in this years GSSOC? If so, you can contribute to this project from March so that you can earn the points of contribution. If not you can contribute to it right away.

**Comment by diksh735** [comment]
Yes, I am participating in it but I would like to start contributing right
away to get familiar with open source.
I hope that is fine!
Another thing all I need to do is fork the repository and push the commits
I make ?
Is that so ?

**Comment by himanshusharma89** [comment]
@diksh735 I recommend you to contribute during GSSOC, to gain the points. And yes, you need to fork the repo, work on your forked repo, push the changes in your forked repo and then create a PR from that forked repo.

**Comment by diksh735** [comment]
There is a menu button on the home page screen. Do you want the App drawer to come up from there? And what all List Tiles do you want to have in the drawer ?

**Comment by himanshusharma89** [comment]
@diksh735 I'll push the illustrations or details soon

**Comment by himanshusharma89** [comment]
Hey, @tiwariadarsh are you participating in GSSOC? If so, you can start form March for gaining the contribution points

**Comment by tiwariadarsh** [comment]
> Hey, @tiwariadarsh are you participating in GSSOC? If so, you can start form March for gaining the contribution points

Yeah I am participating.

**Comment by himanshusharma89** [comment]
@tiwariadarsh Okay, so it would be better to start contributing from March to gain the points

**Comment by tharunc** [comment]
Hello there,
    I would love to contribute to this Issue as a part of **GSSOC'21**. Can you please assign me this issue,
                        THANK YOU

**Comment by diksh735** [comment]
Well I already wanted to do this and reached out first. I hope you will let
me do this part.

**Comment by himanshusharma89** [comment]
No issues, I'll create more issue by tomorrow night.
