### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by himanshusharma89** [himanshusharma89/relic_bazaar#29]

**Comment by Vansh-Gupta4** [comment]
I would like to work on it

**Comment by himanshusharma89** [comment]
Sure @Vansh-Gupta4, but are you participating in GSSOC? If so, it is better to contribute from March to gain the points.

**Comment by Vansh-Gupta4** [comment]
Yes, I am participating in GSSOC..... but isn't this first come first serve
basis(please dont judge because i new to open source)

**Comment by ajay963** [comment]
i am new to open source project and i have'nt participated in GSSOC  but i want to contribute to this project can i ??

**Comment by himanshusharma89** [comment]
@Vansh-Gupta4 Yeah, but all contributions starts from March

**Comment by himanshusharma89** [comment]
@ajay963 Sure, you can contribute to the project

**Comment by piyushpradhan** [comment]
Can I work on this ? I'd really like to contribute to this project.

**Comment by himanshusharma89** [comment]
Sure, @piyushpradhan, you can contribute to this project. And if you are participating in GSSOC, you can read the above comments.

**Comment by piyushpradhan** [comment]
Yes, I am participating in GSSOC. Thank you.

**Comment by himanshusharma89** [comment]
@Vansh-Gupta4 assigning it to you as you commented on it earlier. And @piyushpradhan, you can comment on any other issue.

**Comment by Vansh-Gupta4** [comment]
Thanks alot

**Comment by Vansh-Gupta4** [comment]
i have to write "about page"...right?

**Comment by himanshusharma89** [comment]
@Vansh-Gupta4 You need to create an About Page, for reference you can check out other apps containing about page ut make sure to create it in a retro theme.

**Comment by Vansh-Gupta4** [comment]
where i can check other apps containing about page

**Comment by himanshusharma89** [comment]
@Vansh-Gupta4 You can refer to this:
![image](https://user-images.githubusercontent.com/44980497/110325350-3b3ac600-803d-11eb-9000-6da143144645.png)

**Comment by Vansh-Gupta4** [comment]
thanks @himanshusharma89 i have to make it using html and css ..right?

**Comment by himanshusharma89** [comment]
No @Vansh-Gupta4, this is a Flutter based project.

**Comment by Vansh-Gupta4** [comment]
but i dont know flutter

**Comment by himanshusharma89** [comment]
You should have checked it earlier before commenting, but no issues you can contribute to other projects who have the web tech stack.

**Comment by Vansh-Gupta4** [comment]
ohkk..thankyou  @himanshusharma89

**Comment by piyushpradhan** [comment]
If @Vansh-Gupta4 isn't going to work on this issue, can I be assigned this issue ?

**Comment by himanshusharma89** [comment]
@piyushpradhan one person can work on one issue at a-time, so that everyone can contribute to the project.

**Comment by piyushpradhan** [comment]
Ohh okay, got it!

**Comment by pratikbaid3** [comment]
@himanshusharma89 if no one is working on this, I'd like to work on it.

**Comment by himanshusharma89** [comment]
Hey @pratikbaid3, are you participating in GSSOC?

**Comment by pratikbaid3** [comment]
Yes I am @himanshusharma89

**Comment by D-Ajay-Kumar** [comment]
If the issue is still open I can work on it.

**Comment by pratikbaid3** [comment]
@D-Ajay-Kumar I am currently working on this and will create a PR soon

**Comment by D-Ajay-Kumar** [comment]
All the best man

**Comment by himanshusharma89** [comment]
@pratikbaid3 Is this issue resolved?

**Comment by pratikbaid3** [comment]
@himanshusharma89 I am currently working on #69 as that is a prerequisite, I'll be finishing that in some time and then do this.

**Comment by pratikbaid3** [comment]
@himanshusharma89 #69 is taking some time. If someone else is willing to work on this issue, you can assign them. I'll first have to fix #69 anyways before I can start with this.

**Comment by himanshusharma89** [comment]
@pratikbaid3 Okay, I'll assign it to someone else, if he/she commented before that issue is resolved.

**Comment by D-Ajay-Kumar** [comment]
Can do it

**Comment by D-Ajay-Kumar** [comment]
On it

**Comment by D-Ajay-Kumar** [comment]
How do these look?

![WhatsApp Image 2021-03-14 at 9 16 47 PM](https://user-images.githubusercontent.com/56850266/111074847-07fba980-850b-11eb-96c2-60bbf4b8231b.jpeg)
![WhatsApp Image 2021-03-14 at 9 17 02 PM](https://user-images.githubusercontent.com/56850266/111074849-0e8a2100-850b-11eb-9126-ba2e5b36ef5d.jpeg)

**Comment by himanshusharma89** [comment]
@D-Ajay-Kumar Looks good, create a PR. I hope you are following all the lining rules and making sure that you commit to finalise your work.

**Comment by D-Ajay-Kumar** [comment]
Done. Please check the code :)
