### ISSUE TITLE
Remove Scroll Glow in Horizontal PageView

### ISSUE THREAD

**Issue by himanshusharma89** [himanshusharma89/relic_bazaar#32]
Remove the scroll glow while scrolling through screens in the main.dart

**Comment by Samdid** [comment]
@himanshusharma89  I would like to work on this

**Comment by rudranshawasthi** [comment]
I think I can fix this

**Comment by himanshusharma89** [comment]
@rudranshawasthi Are you participating in GSSOC?

**Comment by rudranshawasthi** [comment]
> @rudranshawasthi Are you participating in GSSOC?

yes

**Comment by srisatya1197** [comment]
I want to contribute to Remove Scroll glow in horizontal pageview issue. Please assign me this task as a part of GSSoC'21

**Comment by himanshusharma89** [comment]
Any update @rudranshawasthi?

**Comment by rudranshawasthi** [comment]
my system crashed

**Comment by D-Ajay-Kumar** [comment]
Anyone still on it or can I take it?

**Comment by himanshusharma89** [comment]
> my system crashed

So would you be able to resolve this issue?

**Comment by D-Ajay-Kumar** [comment]
The issue is being resolved or not? I might be able to help if there's some problem you're facing @rudranshawasthi

**Comment by himanshusharma89** [comment]
> The issue is being resolved or not? I might be able to help if there's some problem you're facing @rudranshawasthi

I guess this issue has taken a lot of time. I'll assign this to you. Make sure to remove the glow globally from the root(main.dart).

**Comment by D-Ajay-Kumar** [comment]
On it @himanshusharma89

**Comment by D-Ajay-Kumar** [comment]
Done. Please check the code. And also I had to fix some other errors that were causing build to fail because I had to check if scroll was removed after building the app with new code.

**Comment by D-Ajay-Kumar** [comment]
Here, this only removes the scroll glow and doesn't affect other files :)
