### ISSUE TITLE
Cart Screen

### ISSUE THREAD

**Issue by himanshusharma89** [himanshusharma89/relic_bazaar#33]
Update the UI for the Cart screen

**Comment by Neha62-lit** [comment]
I would like to work on this issue as a part of GSSOC'21!!

**Comment by himanshusharma89** [comment]
Sure, @Neha62-lit. Let's wait for the coding period to start

**Comment by Neha62-lit** [comment]
@himanshusharma89 Can I start working on this issue??

**Comment by himanshusharma89** [comment]
Sure @Neha62-lit, I am assigning it to you, but we have to wait till this PR #60  is merged. For this issue, you need to remove all the custom height and use Flexible or other widgets so that the cart looks responsive in all devices.

**Comment by Neha62-lit** [comment]
> Sure @Neha62-lit, I am assigning it to you, but we have to wait till this PR #60 is merged. For this issue, you need to remove all the custom height and use Flexible or other widgets so that the cart looks responsive in all devices.

Okay! 🙌

**Comment by himanshusharma89** [comment]
@Neha62-lit you can start working on this issue. The PR id merged. And make sure to do git pull before working.

**Comment by Neha62-lit** [comment]
Sure! 

> @Neha62-lit you can start working on this issue. The PR id merged. And make sure to do git pull before working.

**Comment by Neha62-lit** [comment]
> Sure @Neha62-lit, I am assigning it to you, but we have to wait till this PR #60 is merged. For this issue, you need to remove all the custom height and use Flexible or other widgets so that the cart looks responsive in all devices.

@himanshusharma89  Can you explain me again, what I have to do in these screen?I'm little bit confused!!

**Comment by himanshusharma89** [comment]
@Neha62-lit For the cart screen, you need to make sure for the following:

- [ ] There is no overflow in the screen.
- [ ] Make the screen responsive using MediaQuery, but if still facing the issue of overflow try Expanded or Flexible Widgets.
- [ ] Divide the code into multiple sections for better readability and call these methods in the Column

**Comment by Neha62-lit** [comment]
> @Neha62-lit For the cart screen, you need to make sure for the following:
> 
> * [ ]  There is no overflow in the screen.
> * [ ]  Make the screen responsive using MediaQuery, but if still facing the issue of overflow try Expanded or Flexible Widgets.
> * [ ]  Divide the code into multiple sections for better readability and call these methods in the Column

Okay!! Got it👍
