### ISSUE TITLE
Wishlist Screen

### ISSUE THREAD

**Issue by himanshusharma89** [himanshusharma89/relic_bazaar#35]
Create a retro theme based UI for the Wishlist screen

**Comment by Manzee1609** [comment]
I would like to work on this issue! :)

**Comment by ThatOneTallKid** [comment]
Hey , please assigned this issue to me

**Comment by rudranshawasthi** [comment]
I would like to work on this

**Comment by himanshusharma89** [comment]
@ThatOneTallKid @rudranshawasthi both of you commented around the same time, but I'll assign this issue to @ThatOneTallKid as he commented here first. Also, @rudranshawasthi you can check other issues or you can create issues if you find something in the app.

**Comment by himanshusharma89** [comment]
@ThatOneTallKid Keep in mind to create a retro theme based wishlist, you can check the current wishlist in Profile and replicate it in the new screen. Later when the buttons are added, you can Navigate to Wishlist from the profile.

**Comment by ThatOneTallKid** [comment]
Sure !

**Comment by ThatOneTallKid** [comment]
Hey @himanshusharma89  , I encountered some design flaws like renderflex overflow so should I fix it ? Or you have any other plans for it ?

**Comment by himanshusharma89** [comment]
@ThatOneTallKid It must be resolved by now, pull the latest code.

**Comment by ThatOneTallKid** [comment]
@himanshusharma89  got it!

**Comment by ThatOneTallKid** [comment]
how do we navigate to the wishlist ??
through the drawer or through the profile section?
@himanshusharma89

**Comment by himanshusharma89** [comment]
> how do we navigate to the wishlist ??
> through the drawer or through the profile section?
> @himanshusharma89

We'll go through the profile section for now.

**Comment by ThatOneTallKid** [comment]
OK!

**Comment by ThatOneTallKid** [comment]
![Uploading WhatsApp Image 2021-03-14 at 2.22.45 PM.jpeg…]()
