### ISSUE TITLE
My Order Screen

### ISSUE THREAD

**Issue by himanshusharma89** [himanshusharma89/relic_bazaar#36]
Remove the My Order from Profile and create a new screen similar to that.

**Comment by Samdid** [comment]
@himanshusharma89  I would like to work on this, please assign it to me

**Comment by himanshusharma89** [comment]
Sure @Samdid, let's wait for the coding period to start in GSSOC, then I'll assign it to you.

**Comment by rupanshi-chawda** [comment]
Hey @himanshusharma89, I would like to work on this issue. Please assign it to me.

**Comment by himanshusharma89** [comment]
Hey @rupanshi-chawda, are you participating in GSSOC?

**Comment by rupanshi-chawda** [comment]
> Hey @rupanshi-chawda, are you participating in GSSOC?

Yes, I'm a participant of GSSoC'21

**Comment by himanshusharma89** [comment]
> Yes, I'm a participant of GSSoC'21

Assigned.
