### ISSUE TITLE
Hide Keyboard 

### ISSUE THREAD

**Issue by himanshusharma89** [himanshusharma89/relic_bazaar#37]
Change the focus to hide the keyboard, whenever the user taps on the screen other than the keyboard

**Comment by Neha62-lit** [comment]
@himanshusharma89 I would like to work on it!!

**Comment by diksh735** [comment]
I have added the same and created a pull request kindly check the same.

**Comment by RGTechno** [comment]
@himanshusharma89 I would like to work on this issue. Could you please assign this issue to me?

**Comment by himanshusharma89** [comment]
Sure @RGTechno, assigning it to you.

**Comment by abhishek7997** [comment]
I would like to work on this issue. I am a participant of GSSOC 21. I have some experience in flutter development. So, please assign this issue to me.

**Comment by RGTechno** [comment]
@himanshusharma89 yes i am a participant in gssoc 21
