### ISSUE TITLE
Settings Screen

### ISSUE THREAD

**Issue by himanshusharma89** [himanshusharma89/relic_bazaar#38]
Create Settings Screen containing:

- [x] Your Orders Screen
- [x] Change User Name/Password Screen
- [x] FAQs Screen 
- [x] Log Out Button 
- [x] Manage Address
- [ ] Notification(enable or disable): @anotherwebguy 
- [x] T&C
- [x] GitHub Repo Link Button: Open the in-app web view

**Comment by ritvij14** [comment]
@himanshusharma89 I would like to work on this issue. Also, do these tasks need to be completed in multiple PRs or in a single PR?

**Comment by himanshusharma89** [comment]
@ritvij14 Are you participating in GSSOC? If so, I'll assign it to you.

For this issue, you need a settings icon on the top right corner of the profile screen which will then navigate to the settings screen.
The settings screen will contain the list of the above-mentioned tasks, some of them will have a new page some of them don't. You can start with one task at a time.

**Comment by ritvij14** [comment]
@himanshusharma89 yes I am participating in GSSOC '21 as a mentee. 

Ok got it. So for now to get an idea of the project I would like to go ahead with the Logout button and FAQs section. Does FAQ have a button that leads to a webpage with FAQs or are we showing them in the app itself?

**Comment by himanshusharma89** [comment]
@ritvij14 You can start with the FAQs section, you can get the free FAQs content online and use PDF Viewer to display it

**Comment by himanshusharma89** [comment]
@ritvij14 The settings icon on the profile will be taken care of by someone else.

**Comment by DevilAJ** [comment]
I would like to work on setting icon under Gssoc'21

**Comment by ritvij14** [comment]
> @ritvij14 You can start with the FAQs section, you can get the free FAQs content online and use PDF Viewer to display it

@himanshusharma89 sorry but I am a bit confused 😅, like how many questions and what material/questions should be answered in them etc.
And should I go ahead with this for showing the pdf? https://pub.dev/packages/native_pdf_view

**Comment by himanshusharma89** [comment]
@DevilAj, you can comment on any other issue, these are assigned to others.

@ritvij14 You can refer to this: https://github.com/himanshusharma89/flutterx100/blob/master/lib/helpers/constants.dart
You'll get an idea of FAQs. And yes you can use this package. Make sure to make it not scrollable.

**Comment by ritvij14** [comment]
@himanshusharma89 sorry about the late updates, I started working on this and was wondering if you have a mockup of the settings and faq screens prepared? I just wanted to have a look to get an understanding of how they would work.

**Comment by himanshusharma89** [comment]
> @himanshusharma89 sorry about the late updates, I started working on this and was wondering if you have a mockup of the settings and faq screens prepared? I just wanted to have a look to get an understanding of how they would work.

You can check the Profile Screen and create a similar title for the FAQs and use the expansionTile to display the FAQs, similar to this: https://100daysofflutter.azurewebsites.net/#/ 
Code: https://github.com/himanshusharma89/flutterx100/blob/master/lib/screens/faqs.dart

**Comment by ritvij14** [comment]
@himanshusharma89 I created a mockup of the FAQs screen, but I have a doubt, in the link you sent me of 100daysofflutter, there the FAQ are shown as widgets themselves and not shown in a pdf, That's why I made this ->
![WhatsApp Image 2021-03-10 at 7 48 31 PM](https://user-images.githubusercontent.com/51456744/110643279-ef715380-81d9-11eb-8b1d-471cfb9204c8.jpeg)


Does this look ok? Or do you want me to make any changes? Also, you said about using a package for pdf so how am I supposed to do that here?

**Comment by himanshusharma89** [comment]
@ritvij14 Oh sorry, don't mind the expansionTile we will use PDF Viewer. Also, the settings screen will consist of a list of tiles which will then open a new screen. So FAQ is one of the list tiles, which will open a new screen consisting of the PDF View. 

For PDF View you need a doc, you can just copy-paste the FAQs for now and then import in assets and use it with the package.

**Comment by anotherwebguy** [comment]
> Create Settings Screen containing:
> 
> * [ ]  Your Orders Screen
> * [ ]  Change User Name/Password
> * [ ]  FAQs Screen: @ritvij14
> * [ ]  Log Out Button
> * [ ]  Manage Address
> * [ ]  Notification(enable or disable)
> * [ ]  T&C
> * [ ]  GitHub Repo Link Button

Hey @himanshusharma89  can i work on your orders screen? Plz assign this issue to me ,
Here i just to have to make the mockup for your orders screen right like the one in the profile screen? Bcoz we don't have real data from firebase at present

**Comment by anotherwebguy** [comment]
> Create Settings Screen containing:
> 
> * [ ]  Your Orders Screen
> * [ ]  Change User Name/Password
> * [ ]  FAQs Screen: @ritvij14
> * [ ]  Log Out Button
> * [ ]  Manage Address
> * [ ]  Notification(enable or disable)
> * [ ]  T&C
> * [ ]  GitHub Repo Link Button

can i create work on the setting screen creating all those buttons ? 
plz assign me this issue @himanshusharma89

**Comment by himanshusharma89** [comment]
@anotherwebguy You can select a single button from the issue and wait for this PR to be merged: #108

**Comment by anotherwebguy** [comment]
> @anotherwebguy You can select a single button from the issue and wait for this PR to be merged: #108

Actually i've designed the layout of the settings screen

https://user-images.githubusercontent.com/66346161/110945858-37bc7d00-8364-11eb-8a49-6ef14b36ad67.mp4

![image](https://user-images.githubusercontent.com/66346161/110945902-49058980-8364-11eb-911e-fa587b6300ed.png)

**Comment by anotherwebguy** [comment]
> > @anotherwebguy You can select a single button from the issue and wait for this PR to be merged: #108
> 
> Actually i've designed the layout of the settings screen
> 
>  WhatsApp.Video.2021-03-12.at.6.52.29.PM.mp4 
> ![image](https://user-images.githubusercontent.com/66346161/110945902-49058980-8364-11eb-911e-fa587b6300ed.png)

does this looks good?

**Comment by himanshusharma89** [comment]
> ![image](https://user-images.githubusercontent.com/66346161/110945902-49058980-8364-11eb-911e-fa587b6300ed.png)

Yeah, this looks good, @ritvij14 you can follow this design. And also, the Settings screen might be integrated by tonight, so you can integrate your work into it. Also, @anotherwebguy I'll assign you some part of this issue as soon as the profile fix is merged.

**Comment by anotherwebguy** [comment]
> > ![image](https://user-images.githubusercontent.com/66346161/110945902-49058980-8364-11eb-911e-fa587b6300ed.png)
> 
> Yeah, this looks good, @ritvij14 you can follow this design. And also, the Settings screen might be integrated by tonight, so you can integrate your work into it. Also, @anotherwebguy I'll assign you some part of this issue as soon as the profile fix is merged.

so after the profile fix is merged i should integrate the settings layout into it right?

**Comment by himanshusharma89** [comment]
@anotherwebguy Not the whole screen and buttons, but the layout only.

**Comment by anotherwebguy** [comment]
> @anotherwebguy Not the whole screen and buttons, but the layout only.

yeah only this layout i mean bcoz the functionality of the buttons will be designed by others right?

**Comment by himanshusharma89** [comment]
Yes @anotherwebguy

**Comment by Samdid** [comment]
@himanshusharma89 can I work on change username and password screen?

**Comment by ShrutiJ-01** [comment]
@himanshusharma89 I would like to work on the github repo link button

**Comment by himanshusharma89** [comment]
> @himanshusharma89 can I work on change username and password screen?

Sure, but follow the current layout

**Comment by himanshusharma89** [comment]
> @himanshusharma89 I would like to work on the github repo link button

Sure but the button is already linked, can you add the in-app web view on pressing the button?

**Comment by ShrutiJ-01** [comment]
Yes, I would like to try that

**Comment by himanshusharma89** [comment]
> Yes, I would like to try that

You are assigned, follow the current theme to create the in-app web view

**Comment by anotherwebguy** [comment]
Hey @himanshusharma89  i would like to work on the change addressed screen. Plz assign me this issue. Thanks:)

**Comment by ritvij14** [comment]
@himanshusharma89 sorry about late updates but because of some reasons I will be unable to contribute to this issue. Please give my task to someone else.

**Comment by anotherwebguy** [comment]
Well i can work on the the faqs screen with pdf viewer after i'am done with manage address screen

**Comment by himanshusharma89** [comment]
Sure @anotherwebguy

**Comment by anotherwebguy** [comment]
hello @himanshusharma89 sir i've created the manage address screen plz take a look
should i  make a pr now?

https://user-images.githubusercontent.com/66346161/111302184-15cf3d00-8679-11eb-96a8-529cbbd93ad7.mp4

**Comment by anotherwebguy** [comment]
So now can i work on faq's screen @himanshusharma89

**Comment by anotherwebguy** [comment]
https://user-images.githubusercontent.com/66346161/111579552-349a1480-87dc-11eb-88c7-661703a41162.mp4

Sir i've designed the faqs screen plz take a look @himanshusharma89 
Shoul i make a pr now?

**Comment by himanshusharma89** [comment]
@ShrutiJ-01 Any update on your part?

**Comment by ShrutiJ-01** [comment]
@himanshusharma89 Almost there, will be making PR soon

**Comment by himanshusharma89** [comment]
@ShrutiJ-01 Facing any issue?

**Comment by SapinderSingh** [comment]
@himanshusharma89 I want to work on the T&C Screen.

**Comment by himanshusharma89** [comment]
@ShrutiJ-01 Any update?

**Comment by anotherwebguy** [comment]
> @ShrutiJ-01 Any update?

Should i do it ?

**Comment by ShrutiJ-01** [comment]
@himanshusharma89 Extremely sorry! couldn't finish it on time because of exams.I Will make a PR today itself

**Comment by SapinderSingh** [comment]
@himanshusharma89 I would like to work on the Logout button.

**Comment by anotherwebguy** [comment]
> Create Settings Screen containing:
> 
> * [x]  Your Orders Screen
> * [x]  Change User Name/Password Screen
> * [x]  FAQs Screen
> * [ ]  Log Out Button: @SapinderSingh
> * [x]  Manage Address
> * [ ]  Notification(enable or disable)
> * [x]  T&C
> * [x]  GitHub Repo Link Button: Open the in-app web view

i have already added the notification toggle button in the settings screen is there anything else related to it that needs to be done? i can work on it then?

**Comment by himanshusharma89** [comment]
@anotherwebguy We'll have a particular screen for this also, where user can choose to enable disable the notification

**Comment by himanshusharma89** [comment]
@anotherwebguy Yes you can but do follow the lining rules and resolve the problems(don't ignore them) also don't use Extra widgets for anything unnecessary. I have to clean the code letter. The screen will consist of some text on top which will tell user what does this do and below it, we will have a ListTile for toggle as trailing

**Comment by anotherwebguy** [comment]
> @anotherwebguy Yes you can but do follow the lining rules and resolve the problems(don't ignore them) also don't use Extra widgets for anything unnecessary. I have to clean the code letter. The screen will consist of some text on top which will tell user what does this do and below it, we will have a ListTile for toggle as trailing

Okay i'll keep that in mind i can work on this plz assign it to me

**Comment by anotherwebguy** [comment]
@himanshusharma89 i'm not able to signup in relic bazar it says invalid request

**Comment by himanshusharma89** [comment]
> @himanshusharma89 i'm not able to signup in relic bazar it says invalid request

Are your trying Google Auth? If so, you need to add your SHA-1 key into the firebase console for that.

**Comment by anotherwebguy** [comment]
> > @himanshusharma89 i'm not able to signup in relic bazar it says invalid request
> 
> Are your trying Google Auth? If so, you need to add your SHA-1 key into the firebase console for that.

No iwas trying email auth but it isn't working for me can u plz add my sha keys on firebase so atleast i can login through google auth and work on the issue if yes then i'll share my sha keys over discord dm to you?

**Comment by himanshusharma89** [comment]
Sure @anotherwebguy

**Comment by anotherwebguy** [comment]
![image](https://user-images.githubusercontent.com/66346161/114024156-58a7bd80-9891-11eb-9dee-d89ba2b93fd2.png)

should i  make a pr now @himanshusharma89 ?

**Comment by himanshusharma89** [comment]
@anotherwebguy Just make sure that you use already created Widget for the stacked view

**Comment by anotherwebguy** [comment]
> @anotherwebguy Just make sure that you use already created Widget for the stacked view

Yes i've used that only @himanshusharma89 
So i am making the pr tomorrow the
