### ISSUE TITLE
Use Named Routes

### ISSUE THREAD

**Issue by himanshusharma89** [himanshusharma89/relic_bazaar#43]
Use Named Routes with onGenerateROute in the whole app.
This issue will be assigned after all the screens are created.

**Comment by SapinderSingh** [comment]
@himanshusharma89 Hello, I want to work on this issue, as I am a participant of GSSOC 21

**Comment by himanshusharma89** [comment]
Sure @SapinderSingh, I'll create a list of screens and share it with you, then you can create the routes.

**Comment by SapinderSingh** [comment]
Okay, Great

**Comment by SapinderSingh** [comment]
@himanshusharma89  Hello Sir, Please provide me the list of screens

**Comment by himanshusharma89** [comment]
> @himanshusharma89 Hello Sir, Please provide me the list of screens

Currently, these are the screens:

- Dashboard: `/`
- Home: `/home`
- Login: `/auth`
- Profile: `/profile`
- Search: `/search`
- Products: `/products`
- Wish List: `/wishlist`
- Cart: `/cart`
- Orders: `/orders`
- Settings: `/settings`
- About: `/about`

Follow this to create routes constants: https://github.com/himanshusharma89/Flutter-Blog-App/blob/master/lib/helpers/constants.dart and generateRoutes: https://github.com/himanshusharma89/Flutter-Blog-App/blob/master/lib/helpers/route_page.dart

For generateRoutes you can use Containers if the page doesn't exist in the app.

**Comment by SapinderSingh** [comment]
The whole app is using bottom navigation bar for navigation to screens. That's why Named routes aren't possible for now, because they need the whole screen. What should I do ?

**Comment by SapinderSingh** [comment]
@himanshusharma89 The Home, Search, Cart And Profile Screens can only be accessed from bottom navigation bar and there is no medium to access the other screens except the Product Specific Page.

**Comment by himanshusharma89** [comment]
@SapinderSingh, we still need them for analytics, just create them for now.
