### ISSUE TITLE
Login Screen

### ISSUE THREAD

**Issue by himanshusharma89** [himanshusharma89/relic_bazaar#44]
Create:
- [x] Sign In screen
- [ ] Sign Up screen: @Neha62-lit

**Comment by Manzee1609** [comment]
I would like to work on this issue

**Comment by Samdid** [comment]
@himanshusharma89 can you please kindly assign it to me?

**Comment by himanshusharma89** [comment]
@Samdid  I'll assign the issues when the GSSOC coding period starts.

**Comment by Samdid** [comment]
@himanshusharma89 can I start working on this issue?

**Comment by himanshusharma89** [comment]
Yes @Samdid

**Comment by Samdid** [comment]
> Yes @Samdid. You can take up Sign In screen only.

Sure👍

**Comment by Neha62-lit** [comment]
@himanshusharma89 Can I work on signUp screen?

**Comment by himanshusharma89** [comment]
Sure @Neha62-lit, but one person can work on one screen at a time.

**Comment by anotherwebguy** [comment]
Hello @himanshusharma89 can i work on the signup screen as a part of gssoc'21? Plz assign this issue to me

**Comment by himanshusharma89** [comment]
> Hello @himanshusharma89 can i work on the signup screen as a part of gssoc'21? Plz assign this issue to me

One person can work on one issue at a time, so you can talk to the other people assigned for the Profile Screen issue.

**Comment by Samdid** [comment]
@himanshusharma89 Can I start working on this UI? Is it good for this issue? As I made this UI on figma, the required font family is not available there so I made that default for now but while coding I will make the changes
![2021-03-11 (3)](https://user-images.githubusercontent.com/70087884/110775169-a0342d00-8284-11eb-8905-eb3fa28e9786.png)

**Comment by himanshusharma89** [comment]
> @himanshusharma89 Can I start working on this UI? Is it good for this issue? As I made this UI on figma, the required font family is not available there so I made that default for now but while coding I will make the changes
> ![2021-03-11 (3)](https://user-images.githubusercontent.com/70087884/110775169-a0342d00-8284-11eb-8905-eb3fa28e9786.png)

Yeah, this looks good to me! Go ahead, create a PR whenever you can.

**Comment by Samdid** [comment]
Okay

**Comment by Samdid** [comment]
@himanshusharma89  login screen is ready please tell me where I have to add that screen?

**Comment by himanshusharma89** [comment]
> @himanshusharma89 login screen is ready please tell me where I have to add that screen?

Add the screen in the views subfolder in lib. Also, make sure to pull the latest code.

**Comment by Samdid** [comment]
Okay

**Comment by himanshusharma89** [comment]
> Okay

Oh, I assigned you 2 issues, complete this one before the next one.

**Comment by himanshusharma89** [comment]
@Samdid Is this issue resolved?

**Comment by Neha62-lit** [comment]
> Sure @Neha62-lit, but one person can work on one screen at a time.

@himanshusharma89  As Login screen is done, can I work on this issue now?

**Comment by himanshusharma89** [comment]
@Neha62-lit Any update?

**Comment by Neha62-lit** [comment]
> @Neha62-lit Any update?

Almost completed, will be making PR soon
