### ISSUE TITLE
AdMob integration

### ISSUE THREAD

**Issue by himanshusharma89** [himanshusharma89/relic_bazaar#45]
Integrate Admob in the app, it is currently in beta.
This issue can be assigned after the products screen is created.

**Comment by sssash18** [comment]
Can I work on this issue @himanshusharma89  ?

**Comment by himanshusharma89** [comment]
Sure, are you participating in GSSOC'21?

**Comment by sssash18** [comment]
Yes I am a participant

**Comment by himanshusharma89** [comment]
Okay, I'll assign it to you. Let me check the Admob docs first and you need to wait until firebase is integrated. I'll update you asap.

**Comment by sssash18** [comment]
Ok 
Thank you for assigning it to me...

**Comment by himanshusharma89** [comment]
@sssash18 You can start working on this issue.

**Comment by sssash18** [comment]
Okay @himanshusharma89  I would start working with it

**Comment by sssash18** [comment]
@himanshusharma89  Can I use this pub [Package](https://pub.dev/packages/google_mobile_ads) for integration.
Also I need to use the development api keys right ?

**Comment by himanshusharma89** [comment]
@sssash18 Yes this is the package and this is the implementation: https://developers.google.com/admob/flutter/quick-start. I'll read it and update you asap. If the test keys are available you can try it.

**Comment by himanshusharma89** [comment]
@sssash18 I have the API key, so go ahead integrate the app with the provided steps. Use placeholder in place of the key. I'll test it myself.

Also, you just need to work until the Initialize the Mobile Ads SDK part in the above article

**Comment by sssash18** [comment]
Yeah sure , I will finsih the integration and get back to you

**Comment by sssash18** [comment]
A question do I have to do it for ios ?

**Comment by himanshusharma89** [comment]
> A question do I have to do it for ios ?

Only for Android for now
