### ISSUE TITLE
Create Ads Banner

### ISSUE THREAD

**Issue by himanshusharma89** [himanshusharma89/relic_bazaar#46]
Follow up of #45

**Comment by amanxnanda** [comment]
Hey, @himanshusharma89 I would like to work on this issue, even though I have never worked with ads before. But I feel like it would be a great learning experience.

**Comment by himanshusharma89** [comment]
Sure @amanxnanda, but we need to wait till 8th March for GSSOC coding period to begin. After that we’ll discuss about where to place the ads in the product screen or whether we should update the product screen

**Comment by amanxnanda** [comment]
Sure

**Comment by himanshusharma89** [comment]
Hey @amanxnanda, are you participating in GSSOC? If so I'll assign this issue to you. 

Also, this issue will be worked upon after #45 is closed.

**Comment by amanxnanda** [comment]
Yes I'm participating

**Comment by Saransh-cpp** [comment]
@amanxnanda I implemented the banner ads in one of my projects, you can check out the file [here](https://github.com/Saransh-cpp/BookRentApp-Chapter3/blob/master/lib/Screens/YourOrders.dart), I hope this helps.

**Comment by amanxnanda** [comment]
@Saransh-cpp  thanks for the reference

**Comment by himanshusharma89** [comment]
> @Saransh-cpp thanks for the reference

Admob is integrated now, you can proceed with it

**Comment by amanxnanda** [comment]
Okay, I'll start right away

**Comment by D-Ajay-Kumar** [comment]
All the best @amanxnanda :)

**Comment by amanxnanda** [comment]
@himanshusharma89 I added the banner ad in the app but there are certain things that I would like to discuss like the placement of the ad, type of ad, etc. 
![WhatsApp Image 2021-03-17 at 09 41 28](https://user-images.githubusercontent.com/34944818/111413858-072e6780-8705-11eb-9583-eefea6be7249.jpeg)

I had to replace the banner ad with the body for testing purposes.

**Comment by himanshusharma89** [comment]
@amanxnanda You can contact us on the relic bazaar discord, we will discuss it there.

**Comment by amanxnanda** [comment]
Here's the new placement, above the bottom navbar. Is this okay should I make a PR now?
![image](https://user-images.githubusercontent.com/34944818/111418799-588f2480-870e-11eb-85e4-c7366d2a4dd6.png)

**Comment by amanxnanda** [comment]
@himanshusharma89 can you please review this?

**Comment by himanshusharma89** [comment]
@amanxnanda this looks good, however can you  try to add it in the products screen too.

**Comment by amanxnanda** [comment]
@himanshusharma89 can you describe how?

**Comment by himanshusharma89** [comment]
@amanxnanda Similar to this screen, you can add the banner in the product_page.dart in the product folder inside the widget folder

**Comment by amanxnanda** [comment]
@himanshusharma89  I added ads on the product page too. Can you please check?

![image](https://user-images.githubusercontent.com/34944818/111440649-8e430600-872c-11eb-8621-f269bc6cb9df.png)
![image](https://user-images.githubusercontent.com/34944818/111440653-900cc980-872c-11eb-8ec7-04ebd8b5ae69.png)
