### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by himanshusharma89** [himanshusharma89/relic_bazaar#47]
Update the readme to list out the following

- [ ] License
- [ ] Code of conduct
- [ ] Contributing

You can follow these:
- https://github.com/himanshusharma89/flutterx100
- https://github.com/smaranjitghose/girlscript_app

**Comment by AmjadNoor** [comment]
@himanshusharma89 ,
Can you assign me please.

**Comment by ishandeveloper** [comment]
@AmjadNoor Are you participating in GSSOC 2021?

**Comment by AmjadNoor** [comment]
@ishandeveloper  No, I am not participating in GSSOC 2021.

**Comment by ishandeveloper** [comment]
Sorry @AmjadNoor, we really appreciate your enthusiasm for contributing to this open-source project. However, This issue is reserved only for GSSOC 2021 participants. 

Can you please take a look at some other issues without 'GSSOC' label, or a much better way could be to create and file your own issue and we'll assign it you.

### Happy Hacking! ✨

**Comment by AmjadNoor** [comment]
Ok

**Comment by himanshusharma89** [comment]
@AmjadNoor if you want to contribute you can check out our other projects

**Comment by AmjadNoor** [comment]
Ok

**Comment by Saransh-cpp** [comment]
@himanshusharma89 I had a doubt, can I be assigned or can I start working on the issue right now or should I comment for assignment from tomorrow i.e. when the coding period for Gssoc start?

**Comment by himanshusharma89** [comment]
@Saransh-cpp You need to comment on a particular issue and then when you get assigned for it, you can start working on it.

**Comment by Saransh-cpp** [comment]
> @Saransh-cpp You need to comment on a particular issue and then when you get assigned for it, you can start working on it.

Can I get assigned now, as it is 8th? I will comment on the issues

**Comment by himanshusharma89** [comment]
Sure @Saransh-cpp

**Comment by Saransh-cpp** [comment]
> Sure @Saransh-cpp

Should I add the GIFs from the repositories mentioned above or should I just add a single line for each of the topic, linking the respective .md file?

**Comment by himanshusharma89** [comment]
@Saransh-cpp I have shared the reference you can follow it to create the contributing.
