### ISSUE TITLE
Integrate Remote Config

### ISSUE THREAD

**Issue by himanshusharma89** [himanshusharma89/relic_bazaar#48]
Integrate Firebase engagement tool remote config

**Comment by DevilAJ** [comment]
I would like to work on this issue.

**Comment by himanshusharma89** [comment]
@DevilAJ 'll assign this to you as soon as the Firebase integration is merged.

**Comment by DevilAJ** [comment]
Now I already have an issue assigned.
For now you can leave it open.
I will ask to assign as soon as I completed that issue.

**Comment by pawan2806** [comment]
As the issue is still open , can you assign it to me @himanshusharma89 under Gssoc'21?

**Comment by himanshusharma89** [comment]
Sure, we will rename the package and update the app on firebase. After this you can start working on it.

**Comment by pawan2806** [comment]
What's the update on this @himanshusharma89 ?

**Comment by himanshusharma89** [comment]
We can work on this now.

> What's the update on this @himanshusharma89 ?
