### ISSUE TITLE
Create auto scroll banners to display products

### ISSUE THREAD

**Issue by himanshusharma89** [himanshusharma89/relic_bazaar#49]
Follow up of #48, use the remote data to display scrollable banners

**Comment by himanshusharma89** [comment]
Sure @VaishnaviSood, but you need to wait for #48 to be resolved. I am assigning it to you, I'll update the status asap.

**Comment by AmarjitM13** [comment]
can you plz assign this issue to me

**Comment by himanshusharma89** [comment]
@AmarjitM13 This issue is on hold for now, we are updating the package name. In the meantime, you can create new issues if you face any.

**Comment by VaishnaviSood** [comment]
Hey @himanshusharma89 ...what's the status of this issue now?

**Comment by himanshusharma89** [comment]
> Hey @himanshusharma89 ...what's the status of this issue now?

As soon as this issue #84 is resolved, we'll move ahead with firebase tooling.

**Comment by Rishabh510** [comment]
> > Hey @himanshusharma89 ...what's the status of this issue now?
> 
> As soon as this issue #84 is resolved, we'll move ahead with firebase tooling.

Since issue #84 is resolved, now we can make a auto scrolling carousel of banners. For now we can implement the code with random images. Do we have the mockups for that? Where are we going to place the carousel. I think we can assign this issue now. @himanshusharma89

**Comment by himanshusharma89** [comment]
Yeah @Rishabh510, we need to discuss where to show that banner. Any suggestions?
I was thinking of adding it to the home screen and remove the Name and all the text above the search.

**Comment by Rishabh510** [comment]
> Yeah @Rishabh510, we need to discuss where to show that banner. Any suggestions?
> I was thinking of adding it to the home screen and remove the Name and all the text above the search.

@himanshusharma89 Yes I was also thinking the same. Then lets go ahead with it.

**Comment by himanshusharma89** [comment]
Hey @VaishnaviSood, do you still want to work upon this issue? If so, you can work on it now as Remote Config is integrated now.

**Comment by SapinderSingh** [comment]
@himanshusharma89 I can work on this issue.

**Comment by himanshusharma89** [comment]
@SapinderSingh Do you want to work on this?

**Comment by SapinderSingh** [comment]
> @SapinderSingh Do you want to work on this?

Please check your Discord

**Comment by Rishabh510** [comment]
> > @SapinderSingh Do you want to work on this?
> 
> Please check your Discord

you can reply here itself as we can assign you the task while you make a PR.

**Comment by SapinderSingh** [comment]
👍
