### ISSUE TITLE
Widget Testing

### ISSUE THREAD

**Issue by himanshusharma89** [himanshusharma89/relic_bazaar#54]
https://flutter.dev/docs/cookbook/testing/widget/introduction

**Comment by piyushpradhan** [comment]
I am participating in GSSOC '21, and I'd like to work on this project. Can I try and work on this issue ?

**Comment by himanshusharma89** [comment]
Sure @piyushpradhan, go ahead.

**Comment by piyushpradhan** [comment]
Okay, thank you @himanshusharma89

**Comment by piyushpradhan** [comment]
@himanshusharma89 please review my PR and kindly tell me what else I need to add in there, or is there any improvements that I need to make.

**Comment by himanshusharma89** [comment]
> @himanshusharma89 please review my PR and kindly tell me what else I need to add in there, or is there any improvements that I need to make.

Sure, will check it soon.
