### ISSUE TITLE
Create MKDocs

### ISSUE THREAD

**Issue by himanshusharma89** [himanshusharma89/relic_bazaar#55]
Use MK DOcs to create documentation of the app, you can refer to https://smaranjitghose.github.io/img_ai_app_boilerplate/getting_started/

We will assign this issue one page at a time. The list of pages will be updated soon.

**Comment by Chirag018** [comment]
Can I work on this ?

**Comment by smaranjitghose** [comment]
> Use MK DOcs to create documentation of the app, you can refer to https://smaranjitghose.github.io/img_ai_app_boilerplate/getting_started/
> 
> We will assign this issue one page at a time. The list of pages will be updated soon.

Try to use the material theme with dark mode and keep the documentation related code in a separate branch

**Comment by Chirag018** [comment]
> Use MK DOcs to create documentation of the app, you can refer to https://smaranjitghose.github.io/img_ai_app_boilerplate/getting_started/
> 
> We will assign this issue one page at a time. The list of pages will be updated soon.

**Comment by Chirag018** [comment]
> Use MK DOcs to create documentation of the app, you can refer to https://smaranjitghose.github.io/img_ai_app_boilerplate/getting_started/
> 
> We will assign this issue one page at a time. The list of pages will be updated soon.

For the entire app or just one page.

**Comment by Chirag018** [comment]
> > Use MK DOcs to create documentation of the app, you can refer to https://smaranjitghose.github.io/img_ai_app_boilerplate/getting_started/
> > We will assign this issue one page at a time. The list of pages will be updated soon.
> 
> Try to use the material theme with dark mode and keep the documentation related code in a separate branch

For the entire app should I document or just one page.

**Comment by himanshusharma89** [comment]
@Chirag018 Create only the home page for now.

**Comment by Rishabh510** [comment]
@Chirag018 Are you working on it? Its been 3 days.

**Comment by himanshusharma89** [comment]
> @Chirag018 Are you working on it? Its been 3 days.

Yeah, let us know if you are facing any issue

**Comment by Chirag018** [comment]
Sir @Rishabh510 , @himanshusharma89  I will update you by today.

**Comment by Rishabh510** [comment]
@himanshusharma89 I think we can assign the issue to someone else.

**Comment by himanshusharma89** [comment]
@Chirag018 Any update?

**Comment by Chirag018** [comment]
@himanshusharma89  sir you can assign this task to someone else
