### ISSUE TITLE
Renderflex overflow at the bottom of cart.dart

### ISSUE THREAD

**Issue by Saransh-cpp** [himanshusharma89/relic_bazaar#57]
## Screenshot

<img src="https://user-images.githubusercontent.com/74055102/110254796-aa210c00-7fb6-11eb-9abf-5b6732a661d9.png"  height="500px"/>

I would like to work on this issue as a part of GSSoC.

**Comment by diksh735** [comment]
I would like to work on the issue .

**Comment by Saransh-cpp** [comment]
Oh yes, I missed that issue. No problem, I will close the PR and the issue.
