### ISSUE TITLE
Initialize the Firebase App

### ISSUE THREAD

**Issue by himanshusharma89** [himanshusharma89/relic_bazaar#62]
Refer to this and initialize the Firebase app: https://firebase.flutter.dev/docs/overview/#installation
You just need to add the await Firebase.initializeApp(); before the runApp method in main.

**Comment by Alifbhanvadiya14** [comment]
@himanshusharma89 I want to work on this issue

**Comment by himanshusharma89** [comment]
@Alifbhanvadiya14 are you participating in GSSOC? If so I’ll assign this to you

**Comment by Alifbhanvadiya14** [comment]
Yes I m participating

**Comment by himanshusharma89** [comment]
Okay, @Alifbhanvadiya14
