### ISSUE TITLE
Create the Product Model

### ISSUE THREAD

**Issue by himanshusharma89** [himanshusharma89/relic_bazaar#63]
Refer to the `constants.dart` and check the product list, you'll get the fields for the model.
Create a folder inside lib named `model` and create file `product.dart` which will contain the model.

**Comment by Alifbhanvadiya14** [comment]
@himanshusharma89 can you assign this to me?

**Comment by himanshusharma89** [comment]
@Alifbhanvadiya14 one person can work on one issue at a time

**Comment by aayushbisen** [comment]
I can work on this.

**Comment by himanshusharma89** [comment]
@aayushbisen One person can only work on one issue at a time.

**Comment by pawan2806** [comment]
@himanshusharma89 can you assign it to me?

**Comment by himanshusharma89** [comment]
@pawan2806 Are you participating in GSSOC?

**Comment by pawan2806** [comment]
yes @himanshusharma89
