### ISSUE TITLE
Remove leading search icon in Home Screen search bar

### ISSUE THREAD

**Issue by aayushbisen** [himanshusharma89/relic_bazaar#74]
![image](https://user-images.githubusercontent.com/41341387/110453907-b3ac9000-80ec-11eb-8bd3-acdc85207ff3.png)

Leading search icon can be removed from Home Screen search bar, since there is already a trailing search button present.

**Comment by Praneeth-rdy** [comment]
Can you please assign this to me? I want to work on this.

**Comment by RGTechno** [comment]
@himanshusharma89 I would like to contribute. Please assign this issue to me. I am GSSOC'21 participant

**Comment by AbhipsaGuru1012** [comment]
@himanshusharma89 can I work on this issue?

**Comment by Mohitmadhav** [comment]
@himanshusharma89 can I work on this Issue? I'm also a GSSoC participant

**Comment by srisatya1197** [comment]
I want to contribute to Remove leading search icon in Home Screen search bar issue. Please assign me this task as a part of GSSoC'21

**Comment by ishanailwal** [comment]
@himanshusharma89 can I work on this?

**Comment by ishanailwal** [comment]
Can I work on this?

**Comment by himanshusharma89** [comment]
One person can work on one issue at a time, so I am thinking of assigning this to someone who has not yet worked on any issue yet and he/she commented on this issue earlier.
