### ISSUE TITLE
Pull request template

### ISSUE THREAD

**Issue by Sloth-Panda** [himanshusharma89/relic_bazaar#78]
would like to add  it . please assign it to me @himanshusharma89

**Comment by himanshusharma89** [comment]
@Sloth-Panda One person can work on one issue at a time and one person is already working, on this. If he/she doesn't respond back soon, I'll assign this to you, after your earlier PR is merged.

**Comment by Sloth-Panda** [comment]
@himanshusharma89 I think I did not see this so raised the issue else I would not have

**Comment by himanshusharma89** [comment]
Yeah, @Sloth-Panda, I told the person to create an issue, but you did it earlier. No issues, if I receive no response you'll be assigned to it.

**Comment by Praneeth-rdy** [comment]
Thank you @himanshusharma89.
I can now start working on this issue. Please assign this to me.
