### ISSUE TITLE
Change the Package Name 

### ISSUE THREAD

**Issue by himanshusharma89** [himanshusharma89/relic_bazaar#84]
@ishandeveloper @anushbhatia @smaranjitghose @Rishabh510
I am thinking of renaming the package/applicationId of the app, any views?

**Comment by nb9960** [comment]
> @puru-ganda @Manzee1609 Manzee1609 @DevilAJ @sssash18 @amanxnanda @nb9960
> 
> Hello everyone, just wanted to let you know we might be updating the package name/ applicationId. So for that, we need to add the project again to the Firebase console. I need your thoughts regarding this, currently, the package name is not related to the project name.

Adding another app under same project in firebase console should work, but the changes in codebase should be done by the same person who adds the app in firebase console.

**Comment by Rishabh510** [comment]
> > @puru-ganda @Manzee1609 Manzee1609 @DevilAJ @sssash18 @amanxnanda @nb9960
> > Hello everyone, just wanted to let you know we might be updating the package name/ applicationId. So for that, we need to add the project again to the Firebase console. I need your thoughts regarding this, currently, the package name is not related to the project name.
> 
> Adding another app under same project in firebase console should work, but the changes in codebase should be done by the same person who adds the app in firebase console.

+1 But I think we can add people as collaborator in Firebase console. But it can be too risky. Therefore, in my opinion it is better that the admin make the necessary changes!

**Comment by himanshusharma89** [comment]
We can add editors in the console, nothing to worry about. I am thinking of assigning this issue to someone and also thinking of the new package name.

**Comment by nb9960** [comment]
Make sure to encode firebase web API key (I would suggest you to generate a new one before releasing in production mode) as you guys are going to use firebase auth and users data would be stored there, so anyone with that key could easily gain access to users data

**Comment by Rishabh510** [comment]
According to the gradle [file](https://github.com/himanshusharma89/relic_bazaar/blob/master/android/app/build.gradle), we haven't yet implemented the release configuration and will be working on debug configuration only until release so there's no problem with that.

**Comment by himanshusharma89** [comment]
@nb9960 The release build will take a lot of time. So I think we can update the package name.

**Comment by nb9960** [comment]
> @nb9960 The release build will take a lot of time. So I think we can update the package name.

Enclosing key is independent of updating name that's why I stated earlier to change it **before release (and not now)** as a step to ensure privacy. For now, package name can be updated.

**Comment by himanshusharma89** [comment]
Okay! So @aayushbisen, would you like to work on this as you proposed this suggestion?

**Comment by believeInJha** [comment]
I would like to work on this as a part of GSSoC, could you please assign it to me and guide me with the process?

**Comment by himanshusharma89** [comment]
> I would like to work on this as a part of GSSoC, could you please assign it to me and guide me with the process?

One person can work on one issue at a time.

**Comment by believeInJha** [comment]
Okay got it @himanshusharma89, I thought I can work on multiple issues, sorry for any inconvenience.

**Comment by himanshusharma89** [comment]
> Okay got it @himanshusharma89, I thought I can work on multiple issues, sorry for any inconvenience.

No issues.

**Comment by aayushbisen** [comment]
> Okay! So @aayushbisen, would you like to work on this as you proposed this suggestion?

Okay I can work on this.

**Comment by himanshusharma89** [comment]
> > Okay! So @aayushbisen, would you like to work on this as you proposed this suggestion?
> 
> Okay I can work on this.

I'll update you with the package name tomorrow.

**Comment by himanshusharma89** [comment]
@aayushbisen The package name we are thinking about is tech.himanshusharma.relicbazaar

**Comment by aayushbisen** [comment]
> @aayushbisen The package name we are thinking about is tech.himanshusharma.relicbazaar

Should I change the package name in firebase json file also?

**Comment by himanshusharma89** [comment]
> Should I change the package name in firebase json file also?

Follow this: https://medium.com/@skyblazar.cc/how-to-change-the-package-name-of-your-flutter-app-4529e6e6e6fc

If everything went perfectly, I'll add this project to the Firebase console.
