### ISSUE TITLE
Facebook Authentication through Firebase

### ISSUE THREAD

**Issue by SamarpanCoder2002** [himanshusharma89/relic_bazaar#89]
I would like to add Facebook Authentication With that project

## Context
Facebook Authentication Though Firebase

## Detailed Description
I am also a gssoc'21 participant... I would like to add Facebook authentication to it... If I can forward with that, Please assign me to here...Thank you

**Comment by himanshusharma89** [comment]
@SamarpanCoder2002 We are thinking of adding Facebook Auth for now, but we'll open this PR for future discussion. Thanks for the issue.

**Comment by SamarpanCoder2002** [comment]
> @SamarpanCoder2002 We are thinking of adding Facebook Auth for now, but we'll open this PR for future discussion. Thanks for the issue.

Yah sure... I will wait for the discussion is about to start

**Comment by Mohitmadhav** [comment]
Can I work on this issue @SamarpanCoder2002 and @himanshusharma89 ?

**Comment by himanshusharma89** [comment]
This feature is still not finalised, we'll discuss this whenever the project channel is publically available on GSSOC Discord Server

**Comment by SamarpanCoder2002** [comment]
> This feature is still not finalised, we'll discuss this whenever the project channel is publically available on GSSOC Discord Server

Ok I am waiting for that......

**Comment by pranjalagrawal2012** [comment]
@himanshusharma89 @Mohitmadhav @SamarpanCoder2002 @SapinderSingh @Tushar-OP is this issue active ? and is someone assigned for this issue ??  if not , it will be grateful to work on this issue ?

**Comment by SamarpanCoder2002** [comment]
> > This feature is still not finalised, we'll discuss this whenever the project channel is publically available on GSSOC Discord Server
> 
> Ok I am waiting for that......

If this issue applicable, Please assign me to here...I raised the issue at first

**Comment by himanshusharma89** [comment]
Yeah, if we proceed with this issue I'll assign it to you @SamarpanCoder2002

**Comment by SamarpanCoder2002** [comment]
> Yeah, if we proceed with this issue I'll assign it to you @SamarpanCoder2002

Thanks

**Comment by SamarpanCoder2002** [comment]
> Yeah, if we proceed with this issue I'll assign it to you @SamarpanCoder2002

@himanshusharma89 .... Can now I proceed with that....I am also a GSSOC'21 participant...I I can forward with that...Please assign me to here.....thanks

**Comment by himanshusharma89** [comment]
We don't require Facebook Authentication, so closing this issue.
