### ISSUE TITLE
Renderflex overflow issue in profile page

### ISSUE THREAD

**Issue by anotherwebguy** [himanshusharma89/relic_bazaar#91]
![Screenshot_2021-03-10-11-05-28-966_com example retro_shopping](https://user-images.githubusercontent.com/66346161/110581577-d2646280-8190-11eb-94c9-6aceff0ac74a.jpg)

## I would like to work on fixing this issue under gssoc'21, plz assign me this issue @himanshusharma89

**Comment by himanshusharma89** [comment]
@anotherwebguy This issue already comes under #39
