### ISSUE TITLE
README.md file enhancement

### ISSUE THREAD

**Issue by anirudhsai20** [himanshusharma89/relic_bazaar#93]
The README.md file can be further enhanced by adding a list of all the open source programs in which this project is a part of. Also there are minor grammatical errors that needs correction.

**Comment by anirudhsai20** [comment]
Hi @himanshusharma89 . Please assign me this issue under GSSOC.

**Comment by himanshusharma89** [comment]
Any update @anirudhsai20?

**Comment by anirudhsai20** [comment]
Hi @himanshusharma89 . I will be sending a pull request within an hour.
