### ISSUE TITLE
Widget overflow in  Cart Screen during landscape mode

### ISSUE THREAD

**Issue by saurabhraj042** [himanshusharma89/relic_bazaar#96]
# The PaymentWindow widget overflows in the Cart screen during landscape mode

## Possible Solution
Wrapping the PaymentWindow widget inside a SingleChildeScrollView and OrientationBuilder.Also change in width and height of some components inside it to optimise it for the landscape mode.

## Steps to Reproduce

1.Open the Cart Screen in landscape mode

**Comment by saurabhraj042** [comment]
@himanshusharma89  please assign this issue to me

**Comment by STARLORD3** [comment]
@himanshusharma89 I can work on this?

**Comment by iamsamuelhere** [comment]
@himanshusharma89  can i work on this iam an participant of gssoc

**Comment by saurabhraj042** [comment]
@STARLORD3 @iamsamuelhere  actually I have already fixed this issue ! I will make a PR very soon

**Comment by saurabhraj042** [comment]
My bad , I will make sure to check first before creating an issue !
