### ISSUE TITLE
Drawer Screen Update

### ISSUE THREAD

**Issue by himanshusharma89** [himanshusharma89/relic_bazaar#99]
Update the Drawer Screen for the following:

- [ ] Extract the DrawerWidget from home.dart to a new file called drawer.dart in the views directory.
- [ ] Extract the `_createDrawerItem()` method from home.dart to a new file called drawer_item.dart in widgets directory.
- [ ] Decrease the space and item size in Drawer.

# Discussion 🗣
The Drawer is a unique view in itself, so it should be in the views directory and it's item being widgets can be shifted to the widgets directory as they are the building block of the Drawer no the Drawer itself.

## Detailed Description
This update is required to access al the respective feature with the respective file and also to maintain the code quality.

**Comment by D-Ajay-Kumar** [comment]
Can I do this?

**Comment by himanshusharma89** [comment]
> Can I do this?

Sure

**Comment by D-Ajay-Kumar** [comment]
Thanks. I am starting working on it.

**Comment by D-Ajay-Kumar** [comment]
Done. Please check the code.
